# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""Tests for generators/doh.py — dnsproxy DoH config generator (issue #127)."""
from generators.doh import (
    DOH_BOOTSTRAP_IP,
    generate,
    resolve_upstream_url,
    upstream_needs_bootstrap,
)


class TestNonDohMode:
    def test_manual_mode_emits_empty_string(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "manual"
        assert generate(minimal_state) == ""

    def test_auto_mode_emits_empty_string(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "auto"
        assert generate(minimal_state) == ""


class TestDohMode:
    def test_cloudflare_provider(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "cloudflare"
        out = generate(minimal_state)
        assert 'upstream: ["https://1.1.1.1/dns-query"]' in out

    def test_quad9_provider(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "quad9"
        out = generate(minimal_state)
        assert 'upstream: ["https://9.9.9.9/dns-query"]' in out

    def test_google_provider(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "google"
        out = generate(minimal_state)
        assert 'upstream: ["https://8.8.8.8/dns-query"]' in out

    def test_custom_provider_uses_custom_url(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = "https://doh.example.com/dns-query"
        out = generate(minimal_state)
        assert 'upstream: ["https://doh.example.com/dns-query"]' in out

    def test_custom_provider_without_url_emits_empty_string(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = None
        assert generate(minimal_state) == ""

    def test_header_present(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        out = generate(minimal_state)
        assert out.startswith("# Generated by spud-router")

    def test_listen_address_and_port(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        out = generate(minimal_state)
        assert 'listen-addrs: ["127.0.0.1"]' in out
        assert "listen-ports: [5053]" in out

    def test_cache_enabled(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        out = generate(minimal_state)
        assert "cache: true" in out

    def test_builtin_providers_never_emit_bootstrap(self, minimal_state):
        """IP-pinned built-in providers need no hostname resolution — see
        the block_wan_dns deadlock this dodges (generators/iptables.py)."""
        for provider in ("cloudflare", "quad9", "google"):
            minimal_state["router"]["wan_dns_mode"] = "doh"
            minimal_state["router"]["doh_provider"] = provider
            out = generate(minimal_state)
            assert "bootstrap:" not in out

    def test_custom_hostname_url_emits_bootstrap(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = "https://doh.example.com/dns-query"
        out = generate(minimal_state)
        assert f'bootstrap: ["{DOH_BOOTSTRAP_IP}:53"]' in out

    def test_custom_ip_literal_url_emits_no_bootstrap(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = "https://9.9.9.10/dns-query"
        out = generate(minimal_state)
        assert "bootstrap:" not in out

    def test_upstream_quote_is_escaped(self, minimal_state):
        """Defense in depth: a stray '\"' in a custom URL must not break out
        of the YAML double-quoted upstream literal."""
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = 'https://doh.example.com/x"y'
        out = generate(minimal_state)
        assert 'upstream: ["https://doh.example.com/x\\"y"]' in out


class TestResolveUpstreamUrl:
    def test_defaults_to_cloudflare(self):
        assert resolve_upstream_url({}) == "https://1.1.1.1/dns-query"


class TestUpstreamNeedsBootstrap:
    def test_ip_literal_https_url_false(self):
        assert upstream_needs_bootstrap("https://1.1.1.1/dns-query") is False

    def test_hostname_https_url_true(self):
        assert upstream_needs_bootstrap("https://doh.example.com/dns-query") is True

    def test_empty_url_false(self):
        assert upstream_needs_bootstrap("") is False
