"""Tests for generators/snmp.py — Net-SNMP (snmpd.conf) generator."""
from generators.snmp import generate


def _snmp(**overrides):
    base = {
        "enabled": True,
        "version": "v2c",
        "community_ro": "public",
        "community_rw": "",
        "allowlist": [],
        "bind_interface": "",
        "location": "",
        "contact": "",
    }
    base.update(overrides)
    return base


class TestDisabled:
    def test_disabled_emits_empty_string(self, minimal_state):
        minimal_state["snmp"] = _snmp(enabled=False)
        assert generate(minimal_state) == ""

    def test_missing_snmp_key_emits_empty_string(self, minimal_state):
        assert generate(minimal_state) == ""


class TestAgentAddress:
    def test_no_bind_interface_binds_all(self, minimal_state):
        minimal_state["snmp"] = _snmp(bind_interface="")
        out = generate(minimal_state)
        assert "agentAddress udp:161" in out

    def test_bind_interface_scopes_agent_address(self, minimal_state):
        minimal_state["snmp"] = _snmp(bind_interface="eth0")
        out = generate(minimal_state)
        assert "agentAddress udp:eth0:161" in out


class TestRoCommunity:
    def test_no_allowlist_uses_default_source(self, minimal_state):
        minimal_state["snmp"] = _snmp(community_ro="public", allowlist=[])
        out = generate(minimal_state)
        assert "rocommunity public default" in out

    def test_allowlist_emits_one_line_per_source(self, minimal_state):
        minimal_state["snmp"] = _snmp(community_ro="public", allowlist=["192.168.10.5", "192.168.10.0/24"])
        out = generate(minimal_state)
        assert "rocommunity public 192.168.10.5" in out
        assert "rocommunity public 192.168.10.0/24" in out
        assert "rocommunity public default" not in out


class TestRwCommunity:
    def test_no_rw_community_no_rwcommunity_line(self, minimal_state):
        minimal_state["snmp"] = _snmp(community_rw="")
        out = generate(minimal_state)
        assert "rwcommunity" not in out

    def test_rw_community_set_emits_line(self, minimal_state):
        minimal_state["snmp"] = _snmp(community_rw="private", allowlist=["10.0.0.5"])
        out = generate(minimal_state)
        assert "rwcommunity private 10.0.0.5" in out

    def test_rw_community_no_allowlist_uses_default(self, minimal_state):
        minimal_state["snmp"] = _snmp(community_rw="private", allowlist=[])
        out = generate(minimal_state)
        assert "rwcommunity private default" in out


class TestSysInfo:
    def test_location_and_contact_emitted(self, minimal_state):
        minimal_state["snmp"] = _snmp(location="Server Room", contact="admin@example.com")
        out = generate(minimal_state)
        assert "sysLocation Server Room" in out
        assert "sysContact admin@example.com" in out

    def test_no_location_or_contact_no_lines(self, minimal_state):
        minimal_state["snmp"] = _snmp(location="", contact="")
        out = generate(minimal_state)
        assert "sysLocation" not in out
        assert "sysContact" not in out


class TestHeader:
    def test_has_generated_header(self, minimal_state):
        minimal_state["snmp"] = _snmp()
        out = generate(minimal_state)
        assert out.startswith("# Generated by spud-router")
