"""
Tests for generators/hostapd.py
"""
import pytest
from generators.hostapd import generate, vap_interfaces


@pytest.fixture
def wireless_state(minimal_state, vlan_10, vlan_20):
    state = dict(minimal_state)
    state["vlans"] = [vlan_10, vlan_20]
    state["wireless"] = {
        "enabled": True,
        "interface": "wlan0",
        "country_code": "US",
        "ssids": [
            {
                "id": "aa01",
                "ssid": "HomeNet",
                "vlan_id": 10,
                "band": "2.4",
                "channel": "6",
                "security": "wpa2",
                "password": "supersecret",
                "hidden": False,
                "enabled": True,
            }
        ],
    }
    return state


class TestDisabledWireless:
    def test_disabled_returns_empty(self, minimal_state):
        minimal_state["wireless"] = {"enabled": False, "interface": "wlan0", "country_code": "US", "ssids": []}
        assert generate(minimal_state) == ""

    def test_no_wireless_key_returns_empty(self, minimal_state):
        assert generate(minimal_state) == ""

    def test_enabled_but_no_ssids_returns_empty(self, minimal_state):
        minimal_state["wireless"] = {"enabled": True, "interface": "wlan0", "country_code": "US", "ssids": []}
        assert generate(minimal_state) == ""


class TestBasicGeneration:
    def test_contains_generated_comment(self, wireless_state):
        out = generate(wireless_state)
        assert "Generated by spud-router" in out

    def test_country_code_set(self, wireless_state):
        out = generate(wireless_state)
        assert "country_code=US" in out

    def test_primary_interface_is_vap(self, wireless_state):
        """Primary interface should be a VAP (wlan0_vlan10), not wlan0."""
        out = generate(wireless_state)
        assert "interface=wlan0_vlan10" in out
        # The physical wlan0 should not appear as an interface= line
        assert "interface=wlan0\n" not in out

    def test_bridge_assigned(self, wireless_state):
        out = generate(wireless_state)
        assert "bridge=br-vlan10" in out

    def test_ssid_name(self, wireless_state):
        out = generate(wireless_state)
        assert "ssid=HomeNet" in out

    def test_driver_nl80211(self, wireless_state):
        out = generate(wireless_state)
        assert "driver=nl80211" in out

    def test_channel_set(self, wireless_state):
        out = generate(wireless_state)
        assert "channel=6" in out

    def test_2ghz_hw_mode(self, wireless_state):
        out = generate(wireless_state)
        assert "hw_mode=g" in out

    def test_5ghz_hw_mode(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["band"] = "5"
        wireless_state["wireless"]["ssids"][0]["channel"] = "36"
        out = generate(wireless_state)
        assert "hw_mode=a" in out

    def test_80211n_enabled_on_2ghz(self, wireless_state):
        out = generate(wireless_state)
        assert "ieee80211n=1" in out

    def test_80211ac_enabled_on_5ghz(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["band"] = "5"
        out = generate(wireless_state)
        assert "ieee80211ac=1" in out


class TestSecurity:
    def test_wpa2_config(self, wireless_state):
        out = generate(wireless_state)
        assert "wpa=2" in out
        assert "wpa_key_mgmt=WPA-PSK" in out
        assert "rsn_pairwise=CCMP" in out
        assert "wpa_passphrase=supersecret" in out

    def test_wpa3_config(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["security"] = "wpa3"
        out = generate(wireless_state)
        assert "wpa_key_mgmt=SAE" in out
        assert "sae_password=supersecret" in out
        assert "ieee80211w=2" in out   # PMF required

    def test_wpa2_3_transition(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["security"] = "wpa2/3"
        out = generate(wireless_state)
        assert "wpa_key_mgmt=WPA-PSK SAE" in out
        assert "ieee80211w=1" in out   # PMF optional

    def test_open_has_no_wpa_block(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["security"] = "open"
        out = generate(wireless_state)
        assert "wpa=" not in out
        assert "wpa_passphrase" not in out

    def test_hidden_ssid(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["hidden"] = True
        out = generate(wireless_state)
        assert "ignore_broadcast_ssid=1" in out

    def test_visible_ssid(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["hidden"] = False
        out = generate(wireless_state)
        assert "ignore_broadcast_ssid=0" in out


class TestMultipleSsids:
    def test_second_ssid_uses_bss(self, wireless_state, vlan_20):
        wireless_state["wireless"]["ssids"].append({
            "id": "bb02",
            "ssid": "IoTNet",
            "vlan_id": 20,
            "band": "2.4",
            "channel": "6",
            "security": "wpa2",
            "password": "iotpassword",
            "hidden": False,
            "enabled": True,
        })
        out = generate(wireless_state)
        assert "bss=wlan0_vlan20" in out
        assert "bridge=br-vlan20" in out
        assert "ssid=IoTNet" in out

    def test_disabled_ssid_excluded(self, wireless_state):
        wireless_state["wireless"]["ssids"][0]["enabled"] = False
        out = generate(wireless_state)
        assert out == ""

    def test_ssid_for_nonexistent_vlan_skipped(self, wireless_state):
        """SSIDs referencing VLANs not in state should not appear."""
        wireless_state["wireless"]["ssids"].append({
            "id": "cc03",
            "ssid": "GhostNet",
            "vlan_id": 99,  # doesn't exist
            "band": "2.4",
            "channel": "6",
            "security": "wpa2",
            "password": "password1",
            "hidden": False,
            "enabled": True,
        })
        out = generate(wireless_state)
        assert "GhostNet" not in out


class TestVapInterfaces:
    def test_returns_empty_when_disabled(self, minimal_state):
        assert vap_interfaces(minimal_state) == []

    def test_returns_vap_for_each_ssid(self, wireless_state):
        vaps = vap_interfaces(wireless_state)
        assert len(vaps) == 1
        assert vaps[0]["vap"]     == "wlan0_vlan10"
        assert vaps[0]["bridge"]  == "br-vlan10"
        assert vaps[0]["vlan_if"] == "eth0.10"
        assert vaps[0]["vlan_id"] == 10

    def test_skips_ssid_without_matching_vlan(self, wireless_state):
        wireless_state["wireless"]["ssids"].append({
            "id": "xx", "ssid": "Ghost", "vlan_id": 99,
            "band": "2.4", "channel": "6", "security": "open",
            "password": "", "hidden": False, "enabled": True,
        })
        vaps = vap_interfaces(wireless_state)
        assert all(v["vlan_id"] != 99 for v in vaps)
