# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""Tests for generators/wireguard.py — wg-quick (wg0.conf) generator."""
from generators.wireguard import generate

PRIVATE_KEY = "KX+kU7WXY0KXhioJp/gwTN4v1sgQFgmmF+Tct66W1eg="
PEER_PUBKEY = "aB3kU7WXY0KXhioJp/gwTN4v1sgQFgmmF+Tct66WabC="


def _wg(**overrides):
    base = {
        "enabled": True,
        "mode": "server",
        "listen_port": 51820,
        "private_key": PRIVATE_KEY,
        "address": "10.100.0.1/24",
        "peers": [],
    }
    base.update(overrides)
    return base


class TestDisabled:
    def test_disabled_emits_empty_string(self, minimal_state):
        minimal_state["wireguard"] = _wg(enabled=False)
        assert generate(minimal_state) == ""

    def test_missing_wireguard_key_emits_empty_string(self, minimal_state):
        assert generate(minimal_state) == ""


class TestInterfaceSection:
    def test_private_key_address_port_emitted(self, minimal_state):
        minimal_state["wireguard"] = _wg()
        out = generate(minimal_state)
        assert "[Interface]" in out
        assert f"PrivateKey = {PRIVATE_KEY}" in out
        assert "Address = 10.100.0.1/24" in out
        assert "ListenPort = 51820" in out

    def test_no_address_omits_line(self, minimal_state):
        minimal_state["wireguard"] = _wg(address="")
        out = generate(minimal_state)
        assert "Address" not in out


class TestPeerSection:
    def test_no_peers_no_peer_section(self, minimal_state):
        minimal_state["wireguard"] = _wg(peers=[])
        out = generate(minimal_state)
        assert "[Peer]" not in out

    def test_single_peer_emitted(self, minimal_state):
        minimal_state["wireguard"] = _wg(peers=[{
            "id": "p1", "name": "laptop", "public_key": PEER_PUBKEY,
            "allowed_ips": ["10.100.0.2/32"], "endpoint": None, "persistent_keepalive": None,
        }])
        out = generate(minimal_state)
        assert "[Peer]" in out
        assert "# laptop" in out
        assert f"PublicKey = {PEER_PUBKEY}" in out
        assert "AllowedIPs = 10.100.0.2/32" in out
        assert "Endpoint" not in out
        assert "PersistentKeepalive" not in out

    def test_peer_with_endpoint_and_keepalive(self, minimal_state):
        minimal_state["wireguard"] = _wg(mode="client", peers=[{
            "id": "p1", "name": "home-server", "public_key": PEER_PUBKEY,
            "allowed_ips": ["0.0.0.0/0"], "endpoint": "vpn.example.com:51820",
            "persistent_keepalive": 25,
        }])
        out = generate(minimal_state)
        assert "Endpoint = vpn.example.com:51820" in out
        assert "PersistentKeepalive = 25" in out
        assert "AllowedIPs = 0.0.0.0/0" in out

    def test_multiple_peers_each_get_own_section(self, minimal_state):
        minimal_state["wireguard"] = _wg(peers=[
            {"id": "p1", "name": "a", "public_key": PEER_PUBKEY, "allowed_ips": ["10.100.0.2/32"]},
            {"id": "p2", "name": "b", "public_key": PRIVATE_KEY, "allowed_ips": ["10.100.0.3/32"]},
        ])
        out = generate(minimal_state)
        assert out.count("[Peer]") == 2
        assert "10.100.0.2/32" in out
        assert "10.100.0.3/32" in out


class TestHeader:
    def test_has_generated_header(self, minimal_state):
        minimal_state["wireguard"] = _wg()
        out = generate(minimal_state)
        assert out.startswith("# Generated by spud-router")
