"""
Tests for generators/dnsmasq.py
"""
import pytest
from generators.dnsmasq import generate


class TestDomainConfig:
    def test_domain_from_hostname(self, minimal_state):
        out = generate(minimal_state)
        assert "local=/spud-router.lan/" in out
        assert "domain=spud-router.lan" in out

    def test_custom_hostname(self, minimal_state):
        minimal_state["router"]["hostname"] = "myrouter"
        out = generate(minimal_state)
        assert "local=/myrouter.lan/" in out
        assert "domain=myrouter.lan" in out

    def test_security_directives_present(self, minimal_state):
        out = generate(minimal_state)
        assert "domain-needed" in out
        assert "bogus-priv" in out

    def test_generated_comment_present(self, minimal_state):
        out = generate(minimal_state)
        assert "Generated by spud-router" in out


class TestDhcpScopes:
    def test_vlan_dhcp_scope(self, minimal_state, vlan_10):
        minimal_state["vlans"] = [vlan_10]
        out = generate(minimal_state)
        assert "interface=eth0.10" in out
        assert "dhcp-range=eth0.10,192.168.10.100,192.168.10.200,12h" in out

    def test_dhcp_option_3_gateway(self, minimal_state, vlan_10):
        """DHCP option 3 (default gateway) must point to the VLAN IP."""
        minimal_state["vlans"] = [vlan_10]
        out = generate(minimal_state)
        assert "dhcp-option=eth0.10,3,192.168.10.1" in out

    def test_dhcp_option_6_dns(self, minimal_state, vlan_10):
        """DHCP option 6 (DNS server) must point to the router itself."""
        minimal_state["vlans"] = [vlan_10]
        out = generate(minimal_state)
        assert "dhcp-option=eth0.10,6,192.168.10.1" in out

    def test_vlan_with_dhcp_disabled_not_in_output(self, minimal_state, vlan_10):
        vlan_10["dhcp_enabled"] = False
        minimal_state["vlans"] = [vlan_10]
        out = generate(minimal_state)
        assert "interface=eth0.10" not in out

    def test_multiple_vlan_scopes(self, minimal_state, vlan_10, vlan_20):
        minimal_state["vlans"] = [vlan_10, vlan_20]
        out = generate(minimal_state)
        assert "interface=eth0.10" in out
        assert "interface=eth0.20" in out

    def test_vlan_lease_time_respected(self, minimal_state, vlan_20):
        """vlan_20 has a 6h lease time."""
        minimal_state["vlans"] = [vlan_20]
        out = generate(minimal_state)
        assert "192.168.20.100,192.168.20.200,6h" in out


class TestDnsEntries:
    def test_short_name_gets_two_records(self, minimal_state):
        """Short hostnames resolve as both 'nas' and 'nas.spud-router.lan'."""
        minimal_state["dns_entries"] = [
            {"hostname": "nas", "ip": "192.168.10.10", "description": "TrueNAS"}
        ]
        out = generate(minimal_state)
        assert "address=/nas.spud-router.lan/192.168.10.10" in out
        assert "address=/nas/192.168.10.10" in out

    def test_fqdn_gets_one_record(self, minimal_state):
        """FQDNs (containing a dot) get a single address directive."""
        minimal_state["dns_entries"] = [
            {"hostname": "server.internal.corp", "ip": "10.1.2.3", "description": ""}
        ]
        out = generate(minimal_state)
        assert "address=/server.internal.corp/10.1.2.3" in out
        # Should not get an additional short-name record
        assert out.count("10.1.2.3") == 1

    def test_multiple_dns_entries(self, minimal_state):
        minimal_state["dns_entries"] = [
            {"hostname": "nas",     "ip": "192.168.10.10", "description": ""},
            {"hostname": "proxmox", "ip": "192.168.10.11", "description": ""},
        ]
        out = generate(minimal_state)
        assert "address=/nas/" in out
        assert "address=/proxmox/" in out

    def test_no_dns_entries_no_address_directives(self, minimal_state):
        out = generate(minimal_state)
        assert "address=" not in out


class TestManagementDhcp:
    def test_mgmt_dhcp_scope_when_enabled(self, minimal_state):
        minimal_state["router"]["mgmt_enabled"]   = True
        minimal_state["router"]["mgmt_interface"]  = "eth0"
        minimal_state["router"]["mgmt_ip"]         = "192.168.1.1"
        minimal_state["router"]["mgmt_dhcp_start"] = "192.168.1.100"
        minimal_state["router"]["mgmt_dhcp_end"]   = "192.168.1.150"
        minimal_state["router"]["mgmt_dhcp_lease"] = "12h"
        out = generate(minimal_state)
        assert "interface=eth0" in out
        assert "dhcp-range=eth0,192.168.1.100,192.168.1.150,12h" in out
        assert "dhcp-option=eth0,3,192.168.1.1" in out

    def test_mgmt_dhcp_absent_when_disabled(self, minimal_state):
        minimal_state["router"]["mgmt_enabled"] = False
        out = generate(minimal_state)
        assert "192.168.1.1" not in out
