# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""Tests for generators/bgp.py — FRR BGP config generator (issue #143)."""
from generators.bgp import generate


class TestDisabled:
    def test_disabled_emits_empty_string(self, minimal_state):
        minimal_state["bgp"] = {"enabled": False}
        assert generate(minimal_state) == ""

    def test_missing_bgp_key_emits_empty_string(self, minimal_state):
        assert "bgp" not in minimal_state
        assert generate(minimal_state) == ""

    def test_enabled_without_asn_emits_empty_string(self, minimal_state):
        minimal_state["bgp"] = {"enabled": True, "asn": None, "router_id": "10.0.0.1"}
        assert generate(minimal_state) == ""

    def test_enabled_without_router_id_emits_empty_string(self, minimal_state):
        minimal_state["bgp"] = {"enabled": True, "asn": 65001, "router_id": None}
        assert generate(minimal_state) == ""


class TestEnabled:
    def test_header_present(self, minimal_state):
        minimal_state["bgp"] = {"enabled": True, "asn": 65001, "router_id": "10.0.0.1"}
        out = generate(minimal_state)
        assert out.startswith("! Generated by spud-router")

    def test_router_bgp_and_router_id(self, minimal_state):
        minimal_state["bgp"] = {"enabled": True, "asn": 65001, "router_id": "10.0.0.1"}
        out = generate(minimal_state)
        assert "router bgp 65001" in out
        assert " bgp router-id 10.0.0.1" in out

    def test_single_neighbor(self, minimal_state):
        minimal_state["bgp"] = {
            "enabled": True, "asn": 65001, "router_id": "10.0.0.1",
            "neighbors": [{"ip": "192.168.10.2", "remote_as": 65002, "description": ""}],
        }
        out = generate(minimal_state)
        assert " neighbor 192.168.10.2 remote-as 65002" in out
        assert " neighbor 192.168.10.2 activate" in out
        assert "description" not in out

    def test_neighbor_description_emitted_when_set(self, minimal_state):
        minimal_state["bgp"] = {
            "enabled": True, "asn": 65001, "router_id": "10.0.0.1",
            "neighbors": [{"ip": "192.168.10.2", "remote_as": 65002, "description": "Upstream ISP"}],
        }
        out = generate(minimal_state)
        assert " neighbor 192.168.10.2 description Upstream ISP" in out

    def test_multiple_neighbors(self, minimal_state):
        minimal_state["bgp"] = {
            "enabled": True, "asn": 65001, "router_id": "10.0.0.1",
            "neighbors": [
                {"ip": "192.168.10.2", "remote_as": 65002, "description": ""},
                {"ip": "192.168.10.3", "remote_as": 65003, "description": ""},
            ],
        }
        out = generate(minimal_state)
        assert " neighbor 192.168.10.2 remote-as 65002" in out
        assert " neighbor 192.168.10.3 remote-as 65003" in out
        assert " neighbor 192.168.10.2 activate" in out
        assert " neighbor 192.168.10.3 activate" in out

    def test_advertised_networks(self, minimal_state):
        minimal_state["bgp"] = {
            "enabled": True, "asn": 65001, "router_id": "10.0.0.1",
            "networks": ["10.0.0.0/24", "192.168.10.0/24"],
        }
        out = generate(minimal_state)
        assert "  network 10.0.0.0/24" in out
        assert "  network 192.168.10.0/24" in out

    def test_no_neighbors_no_networks_still_emits_address_family(self, minimal_state):
        minimal_state["bgp"] = {"enabled": True, "asn": 65001, "router_id": "10.0.0.1"}
        out = generate(minimal_state)
        assert " address-family ipv4 unicast" in out
        assert " exit-address-family" in out

    def test_address_family_block_ordering(self, minimal_state):
        """activate lines and network lines must live inside the
        address-family block, which must close with exit-address-family."""
        minimal_state["bgp"] = {
            "enabled": True, "asn": 65001, "router_id": "10.0.0.1",
            "neighbors": [{"ip": "192.168.10.2", "remote_as": 65002, "description": ""}],
            "networks": ["10.0.0.0/24"],
        }
        out = generate(minimal_state)
        lines = out.split("\n")
        af_idx = lines.index(" address-family ipv4 unicast")
        exit_idx = lines.index(" exit-address-family")
        activate_idx = next(i for i, l in enumerate(lines) if "activate" in l)
        network_idx = next(i for i, l in enumerate(lines) if l.startswith("  network"))
        assert af_idx < activate_idx < exit_idx
        assert af_idx < network_idx < exit_idx
