"""Tests for generators/cloudflared.py — DoH proxy env file generator."""
from generators.cloudflared import generate, resolve_upstream_url


class TestNonDohMode:
    def test_manual_mode_emits_empty_string(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "manual"
        assert generate(minimal_state) == ""

    def test_auto_mode_emits_empty_string(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "auto"
        assert generate(minimal_state) == ""


class TestDohMode:
    def test_cloudflare_provider(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "cloudflare"
        out = generate(minimal_state)
        assert "DOH_UPSTREAM=https://cloudflare-dns.com/dns-query" in out

    def test_quad9_provider(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "quad9"
        out = generate(minimal_state)
        assert "DOH_UPSTREAM=https://dns.quad9.net/dns-query" in out

    def test_google_provider(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "google"
        out = generate(minimal_state)
        assert "DOH_UPSTREAM=https://dns.google/dns-query" in out

    def test_custom_provider_uses_custom_url(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = "https://doh.example.com/dns-query"
        out = generate(minimal_state)
        assert "DOH_UPSTREAM=https://doh.example.com/dns-query" in out

    def test_custom_provider_without_url_emits_empty_string(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        minimal_state["router"]["doh_provider"] = "custom"
        minimal_state["router"]["doh_custom_url"] = None
        assert generate(minimal_state) == ""

    def test_header_present(self, minimal_state):
        minimal_state["router"]["wan_dns_mode"] = "doh"
        out = generate(minimal_state)
        assert out.startswith("# Generated by spud-router")


class TestResolveUpstreamUrl:
    def test_defaults_to_cloudflare(self):
        assert resolve_upstream_url({}) == "https://cloudflare-dns.com/dns-query"
