# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""Tests for generators/syslog.py — rsyslog remote-forwarding drop-in."""
from generators.syslog import generate


def _syslog(**overrides):
    base = {
        "enabled": True,
        "server": "logs.example.com",
        "port": 514,
        "protocol": "udp",
        "facility": "*",
        "severity": "*",
        "keep_local": True,
    }
    base.update(overrides)
    return base


class TestDisabled:
    def test_disabled_emits_empty_string(self, minimal_state):
        minimal_state["syslog"] = _syslog(enabled=False)
        assert generate(minimal_state) == ""

    def test_missing_syslog_key_emits_empty_string(self, minimal_state):
        assert generate(minimal_state) == ""


class TestUdp:
    def test_udp_uses_single_at(self, minimal_state):
        minimal_state["syslog"] = _syslog(protocol="udp", server="10.0.0.5", port=514)
        out = generate(minimal_state)
        assert "*.* @10.0.0.5:514" in out
        assert "@@10.0.0.5:514" not in out


class TestTcp:
    def test_tcp_uses_double_at(self, minimal_state):
        minimal_state["syslog"] = _syslog(protocol="tcp", server="10.0.0.5", port=6514)
        out = generate(minimal_state)
        assert "*.* @@10.0.0.5:6514" in out


class TestTls:
    def test_tls_uses_double_at_and_gtls_lines(self, minimal_state):
        minimal_state["syslog"] = _syslog(protocol="tls", server="logs.example.com", port=6514)
        out = generate(minimal_state)
        assert "$DefaultNetstreamDriver gtls" in out
        assert "$ActionSendStreamDriver gtls" in out
        assert "*.* @@logs.example.com:6514" in out


class TestSelector:
    def test_facility_severity_selector(self, minimal_state):
        minimal_state["syslog"] = _syslog(facility="local0", severity="err")
        out = generate(minimal_state)
        assert "local0.err @logs.example.com:514" in out


class TestKeepLocal:
    def test_keep_local_true_no_stop_directive(self, minimal_state):
        minimal_state["syslog"] = _syslog(keep_local=True)
        out = generate(minimal_state)
        assert "& stop" not in out

    def test_keep_local_false_adds_stop_directive(self, minimal_state):
        minimal_state["syslog"] = _syslog(keep_local=False)
        out = generate(minimal_state)
        assert "& stop" in out


class TestHeader:
    def test_has_generated_header(self, minimal_state):
        minimal_state["syslog"] = _syslog()
        out = generate(minimal_state)
        assert out.startswith("# Generated by spud-router")
