# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
FRR BGP config generator (issue #143).

state["bgp"] is validated by models.BgpConfig before it ever reaches this
module — ASN/router_id/neighbor IPs/advertised networks are all strictly
validated (int range, IPv4Address/IPv4Network) — so nothing here needs
further escaping; every interpolated value is already a validated numeric
or IP literal, not user-supplied free text.

IPv4 only, accept-all import/export — no route-maps, prefix-lists, or
community policy (out of scope for #143; see the issue for the full
rationale). Output is the BGP section of /etc/frr/frr.conf, written by
apply_core.py.
"""


def generate(state: dict) -> str:
    """
    Generate the BGP section of /etc/frr/frr.conf.
    Returns "" when BGP is disabled — apply_core.py reloads frr with the
    BGP section absent (rather than stopping the shared frr daemon) in
    that case.
    """
    bgp = state.get("bgp", {})
    if not bgp.get("enabled"):
        return ""

    asn = bgp.get("asn")
    router_id = bgp.get("router_id")
    if asn is None or not router_id:
        return ""

    neighbors = bgp.get("neighbors", [])
    networks = bgp.get("networks", [])

    lines = [
        "! Generated by spud-router — do not edit manually",
        f"router bgp {asn}",
        f" bgp router-id {router_id}",
    ]
    for n in neighbors:
        ip = n["ip"]
        lines.append(f" neighbor {ip} remote-as {n['remote_as']}")
        if n.get("description"):
            lines.append(f" neighbor {ip} description {n['description']}")

    lines.append(" address-family ipv4 unicast")
    for n in neighbors:
        lines.append(f"  neighbor {n['ip']} activate")
    for net in networks:
        lines.append(f"  network {net}")
    lines.append(" exit-address-family")
    lines.append("!")

    return "\n".join(lines) + "\n"
