"""
cloudflared "proxy-dns" environment file generator.

Produces /etc/default/cloudflared-doh: a single DOH_UPSTREAM=<url> line
consumed by the cloudflared-doh.service systemd unit (installed by
install.sh, disabled by default) via EnvironmentFile. The upstream URL has
already been through RouterConfig.valid_doh_custom_url (https:// scheme,
validated host, no shell metacharacters) when doh_provider == "custom", so
nothing here needs further escaping.
"""

DOH_PROVIDER_URLS = {
    "cloudflare": "https://cloudflare-dns.com/dns-query",
    "quad9":      "https://dns.quad9.net/dns-query",
    "google":     "https://dns.google/dns-query",
}


def resolve_upstream_url(router: dict) -> str:
    """Return the DoH upstream URL for the configured provider, or '' if
    unresolvable (e.g. provider == "custom" with no URL set)."""
    provider = router.get("doh_provider", "cloudflare")
    if provider == "custom":
        return router.get("doh_custom_url") or ""
    return DOH_PROVIDER_URLS.get(provider, DOH_PROVIDER_URLS["cloudflare"])


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/default/cloudflared-doh.
    Returns "" when wan_dns_mode isn't "doh" (or the upstream can't be
    resolved) — apply() stops+disables the service in that case.
    """
    router = state.get("router", {})
    if router.get("wan_dns_mode") != "doh":
        return ""

    upstream = resolve_upstream_url(router)
    if not upstream:
        return ""

    return (
        "# Generated by spud-router — do not edit manually\n"
        f"DOH_UPSTREAM={upstream}\n"
    )
