# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
dnsmasq configuration generator.

Produces a dnsmasq config file that provides:
  - Domain configuration (.lan domain)
  - Upstream DNS (auto from WAN DHCP, or manual server= overrides)
  - Custom local A records (address= directives)
  - Management interface DHCP scope (untagged)
  - Per-VLAN DHCP scopes with gateway and DNS options
"""

# systemd-resolved (running with DNSStubListener=no) writes the DHCP-learned
# upstream servers here; dnsmasq reads them in "auto" mode.
RESOLVED_UPSTREAM_FILE = "/run/systemd/resolve/resolv.conf"

# Local port cloudflared's "proxy-dns" mode listens on (see
# generators/cloudflared.py and routers/config.py apply()).
DOH_PROXY_ADDR = "127.0.0.1#5053"


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/dnsmasq.d/spud-router.conf.

    Args:
        state: Full router state dict from state.load_state()

    Returns:
        dnsmasq config string ready to write to disk.
    """
    router       = state.get("router", {})
    vlans        = state.get("vlans", [])
    dns_entries  = state.get("dns_entries", [])

    hostname     = router.get("hostname", "spud-router")
    domain       = f"{hostname}.lan"
    # Absent mode → "manual" so upgraded installs (which have no resolved set up)
    # are fixed immediately rather than pointed at a resolv file that won't exist.
    dns_mode     = router.get("wan_dns_mode", "manual")
    mgmt_enabled = router.get("mgmt_enabled", False)
    mgmt_if      = router.get("mgmt_interface", "eth0")
    mgmt_ip      = router.get("mgmt_ip", "192.168.1.1")
    mgmt_start   = router.get("mgmt_dhcp_start", "192.168.1.100")
    mgmt_end     = router.get("mgmt_dhcp_end", "192.168.1.150")
    mgmt_lease   = router.get("mgmt_dhcp_lease", "12h")

    lines = [
        "# Generated by spud-router — do not edit manually",
        "domain-needed",
        "bogus-priv",
        f"local=/{domain}/",
        f"domain={domain}",
        "",
    ]

    # Upstream resolvers
    if dns_mode == "doh":
        # Point dnsmasq at the local cloudflared "proxy-dns" listener instead
        # of a plaintext upstream — LAN/DHCP/local records are unaffected,
        # only the upstream resolution path changes.
        lines += [
            "# Upstream DNS — DNS-over-HTTPS via local cloudflared proxy",
            "no-resolv",
            f"server={DOH_PROXY_ADDR}",
            "",
        ]
    elif dns_mode == "manual":
        # Use only the configured servers; ignore /etc/resolv.conf entirely.
        upstreams = [s for s in (router.get("wan_dns"), router.get("wan_dns_alt")) if s]
        if not upstreams:
            upstreams = ["1.1.1.1"]
        lines.append("# Upstream DNS — manual")
        lines.append("no-resolv")
        for s in upstreams:
            lines.append(f"server={s}")
        lines.append("")
    else:
        # Follow the WAN DHCP lease via systemd-resolved (stub listener disabled).
        lines += [
            "# Upstream DNS — auto (from WAN DHCP, via systemd-resolved)",
            f"resolv-file={RESOLVED_UPSTREAM_FILE}",
            "",
        ]

    # Custom DNS entries (A records)
    if dns_entries:
        lines.append("# Custom DNS entries")
        for entry in dns_entries:
            hostname_part = entry["hostname"]
            # Resolve both short name and FQDN
            if "." not in hostname_part:
                fqdn = f"{hostname_part}.{domain}"
                lines.append(f"address=/{fqdn}/{entry['ip']}")
                lines.append(f"address=/{hostname_part}/{entry['ip']}")
            else:
                lines.append(f"address=/{hostname_part}/{entry['ip']}")
        lines.append("")

    # Management interface DHCP (untagged direct access)
    if mgmt_enabled:
        lines += [
            "# Management interface (untagged — direct laptop access)",
            f"interface={mgmt_if}",
            f"dhcp-range={mgmt_if},{mgmt_start},{mgmt_end},{mgmt_lease}",
            f"dhcp-option={mgmt_if},3,{mgmt_ip}",   # default gateway
            f"dhcp-option={mgmt_if},6,{mgmt_ip}",   # DNS server (self)
            "",
        ]

    # Per-VLAN DHCP scopes
    for vlan in vlans:
        if not vlan.get("dhcp_enabled"):
            continue
        subif = f"{vlan['interface']}.{vlan['vlan_id']}"
        gw    = vlan["ip_address"]
        dns   = vlan.get("dns_server") or gw
        lines += [
            f"# VLAN {vlan['vlan_id']} — {vlan['name']}",
            f"interface={subif}",
            f"dhcp-range={subif},{vlan['dhcp_start']},{vlan['dhcp_end']},{vlan['dhcp_lease']}",
            f"dhcp-option={subif},3,{gw}",   # default gateway
            f"dhcp-option={subif},6,{dns}",  # DNS server (self, unless overridden)
        ]
        for opt in vlan.get("dhcp_options", []):
            lines.append(f"dhcp-option={subif},{opt}")
        lines.append("")

    return "\n".join(lines)
