# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
dnsmasq configuration generator.

Produces a dnsmasq config file that provides:
  - Domain configuration (.lan domain)
  - Upstream DNS (auto from WAN DHCP, or manual server= overrides)
  - Custom local A records (address= directives)
  - Management interface DHCP scope (untagged)
  - Per-VLAN DHCP scopes with gateway and DNS options
  - Per-VLAN DHCP reservations (dhcp-host= MAC→IP pinning)
"""

# systemd-resolved (running with DNSStubListener=no) writes the DHCP-learned
# upstream servers here; dnsmasq reads them in "auto" mode.
RESOLVED_UPSTREAM_FILE = "/run/systemd/resolve/resolv.conf"

# Local port dnsproxy's DoH-forwarding listener runs on (see
# generators/doh.py and apply_core.py's activate_all()).
DOH_PROXY_ADDR = "127.0.0.1#5053"


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/dnsmasq.d/spud-router.conf.

    Args:
        state: Full router state dict from state.load_state()

    Returns:
        dnsmasq config string ready to write to disk.
    """
    router       = state.get("router", {})
    vlans        = state.get("vlans", [])
    dns_entries  = state.get("dns_entries", [])

    hostname     = router.get("hostname", "spud-router")
    domain       = f"{hostname}.lan"
    # Absent mode → "manual" so upgraded installs (which have no resolved set up)
    # are fixed immediately rather than pointed at a resolv file that won't exist.
    dns_mode     = router.get("wan_dns_mode", "manual")
    mgmt_enabled = router.get("mgmt_enabled", False)
    mgmt_if      = router.get("mgmt_interface", "eth0")
    mgmt_ip      = router.get("mgmt_ip", "192.168.1.1")
    mgmt_start   = router.get("mgmt_dhcp_start", "192.168.1.100")
    mgmt_end     = router.get("mgmt_dhcp_end", "192.168.1.150")
    mgmt_lease   = router.get("mgmt_dhcp_lease", "12h")

    lines = [
        "# Generated by spud-router — do not edit manually",
        "domain-needed",
        "bogus-priv",
        f"local=/{domain}/",
        f"domain={domain}",
        "",
    ]

    # Upstream resolvers
    if dns_mode == "doh":
        # Point dnsmasq at the local dnsproxy DoH-forwarding listener instead
        # of a plaintext upstream — LAN/DHCP/local records are unaffected,
        # only the upstream resolution path changes.
        lines += [
            "# Upstream DNS — DNS-over-HTTPS via local dnsproxy",
            "no-resolv",
            f"server={DOH_PROXY_ADDR}",
            "",
        ]
    elif dns_mode == "manual":
        # Use only the configured servers; ignore /etc/resolv.conf entirely.
        upstreams = [s for s in (router.get("wan_dns"), router.get("wan_dns_alt")) if s]
        if not upstreams:
            upstreams = ["1.1.1.1"]
        lines.append("# Upstream DNS — manual")
        lines.append("no-resolv")
        for s in upstreams:
            lines.append(f"server={s}")
        lines.append("")
    else:
        # Follow the WAN DHCP lease via systemd-resolved (stub listener disabled).
        lines += [
            "# Upstream DNS — auto (from WAN DHCP, via systemd-resolved)",
            f"resolv-file={RESOLVED_UPSTREAM_FILE}",
            "",
        ]

    # Custom DNS entries (A records)
    if dns_entries:
        lines.append("# Custom DNS entries")
        for entry in dns_entries:
            hostname_part = entry["hostname"]
            # Resolve both short name and FQDN
            if "." not in hostname_part:
                fqdn = f"{hostname_part}.{domain}"
                lines.append(f"address=/{fqdn}/{entry['ip']}")
                lines.append(f"address=/{hostname_part}/{entry['ip']}")
            else:
                lines.append(f"address=/{hostname_part}/{entry['ip']}")
        lines.append("")

    # Management interface DHCP (untagged direct access). A tagged
    # management VLAN (mgmt_if containing a dot, e.g. "eth1.99" — #207's
    # 2-NIC mgmt-VLAN composition) is skipped here: it's a real VlanConfig
    # entry in vlans[] and gets its DHCP scope from the per-VLAN loop below,
    # same as any other tagged VLAN. Emitting it here too would duplicate a
    # dhcp-range from a second, independent source (router.mgmt_dhcp_start/
    # end vs. the VLAN entry's own dhcp_start/end) that could drift out of
    # sync if either is edited without the other.
    if mgmt_enabled and "." not in mgmt_if:
        lines += [
            "# Management interface (untagged — direct laptop access)",
            f"interface={mgmt_if}",
            f"dhcp-range={mgmt_if},{mgmt_start},{mgmt_end},{mgmt_lease}",
            f"dhcp-option={mgmt_if},3,{mgmt_ip}",   # default gateway
            f"dhcp-option={mgmt_if},6,{mgmt_ip}",   # DNS server (self)
            "",
        ]

    # Per-VLAN DHCP scopes. vlan_id == 0 is the "untagged / physical
    # interface" sentinel (#195, multi-NIC installs) — the network lives
    # directly on its own port, so dnsmasq's interface= is the bare NIC name
    # rather than a tagged "<if>.<vlan_id>" subinterface.
    for vlan in vlans:
        if not vlan.get("dhcp_enabled"):
            continue
        untagged = vlan.get("vlan_id") == 0
        subif = vlan["interface"] if untagged else f"{vlan['interface']}.{vlan['vlan_id']}"
        gw    = vlan["ip_address"]
        dns   = vlan.get("dns_server") or gw
        label = vlan["name"] if untagged else f"VLAN {vlan['vlan_id']} — {vlan['name']}"
        lines += [
            f"# {label}",
            f"interface={subif}",
            f"dhcp-range={subif},{vlan['dhcp_start']},{vlan['dhcp_end']},{vlan['dhcp_lease']}",
            f"dhcp-option={subif},3,{gw}",   # default gateway
            f"dhcp-option={subif},6,{dns}",  # DNS server (self, unless overridden)
        ]
        for opt in vlan.get("dhcp_options", []):
            lines.append(f"dhcp-option={subif},{opt}")
        for res in vlan.get("dhcp_reservations", []):
            host_line = f"dhcp-host={res['mac']},{res['ip']}"
            if res.get("hostname"):
                host_line += f",{res['hostname']}"
            lines.append(host_line)
        lines.append("")

    return "\n".join(lines)
