# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
dnsproxy DNS-over-HTTPS generator.

Produces /etc/dnsproxy-doh.yaml, a minimal config for AdGuard `dnsproxy`
(github.com/AdguardTeam/dnsproxy), run via dnsproxy-doh.service (installed
by install.sh, disabled by default) as
`dnsproxy --config-path=/etc/dnsproxy-doh.yaml`.

Replaces the former `cloudflared proxy-dns` backend (issue #127): Cloudflare
removed the `proxy-dns` subcommand in cloudflared 2026.2.0, permanently
breaking that path. dnsproxy is a maintained, single static-binary
alternative with the identical local-plaintext-in / DoH-out shape, so
dnsmasq's `server=127.0.0.1#5053` upstream (generators/dnsmasq.py) needs no
change at all.

The upstream URL has already been through RouterConfig.valid_doh_custom_url
(https:// scheme, validated host, no control characters/spaces) when
doh_provider == "custom" — it is still escaped below before being embedded
in the YAML string, as defense in depth against a stray `"` breaking out of
the quoted literal.

Built-in providers resolve to IP-literal DoH endpoints (Cloudflare/Quad9/
Google all serve valid TLS certs for their own anycast IPs), so dnsproxy
never needs to resolve a hostname for them — no bootstrap query, so
block_wan_dns's outbound :53 REJECT (generators/iptables.py) can never starve
them. A "custom" provider's URL may be a hostname instead, which DOES need a
plaintext bootstrap lookup; DOH_BOOTSTRAP_IP is the one fixed resolver used
for that lookup, and generators/iptables.py imports this same constant so
its narrow OUTPUT exception always matches exactly what dnsproxy queries.
"""
import ipaddress
import urllib.parse

DOH_PROVIDER_URLS = {
    "cloudflare": "https://1.1.1.1/dns-query",
    "quad9":      "https://9.9.9.9/dns-query",
    "google":     "https://8.8.8.8/dns-query",
}

# Fixed plaintext resolver used ONLY to bootstrap-resolve a custom DoH
# upstream hostname. Built-in providers are IP-literal and never need this.
DOH_BOOTSTRAP_IP = "1.1.1.1"


def resolve_upstream_url(router: dict) -> str:
    """Return the DoH upstream URL for the configured provider, or '' if
    unresolvable (e.g. provider == "custom" with no URL set)."""
    provider = router.get("doh_provider", "cloudflare")
    if provider == "custom":
        return router.get("doh_custom_url") or ""
    return DOH_PROVIDER_URLS.get(provider, DOH_PROVIDER_URLS["cloudflare"])


def upstream_needs_bootstrap(upstream_url: str) -> bool:
    """
    True when the upstream URL's host is a hostname rather than an IP
    literal, meaning dnsproxy needs a plaintext bootstrap DNS lookup to
    resolve it before it can dial the DoH endpoint itself.
    """
    if not upstream_url:
        return False
    host = urllib.parse.urlparse(upstream_url).hostname
    if not host:
        return False
    try:
        ipaddress.ip_address(host)
        return False   # already an IP literal — no resolution needed
    except ValueError:
        return True


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/dnsproxy-doh.yaml.
    Returns "" when wan_dns_mode isn't "doh" (or the upstream can't be
    resolved) — apply() stops+disables the service in that case.
    """
    router = state.get("router", {})
    if router.get("wan_dns_mode") != "doh":
        return ""

    upstream = resolve_upstream_url(router)
    if not upstream:
        return ""

    upstream_escaped = upstream.replace("\\", "\\\\").replace('"', '\\"')

    lines = [
        "# Generated by spud-router — do not edit manually",
        'listen-addrs: ["127.0.0.1"]',
        "listen-ports: [5053]",
        f'upstream: ["{upstream_escaped}"]',
    ]
    if upstream_needs_bootstrap(upstream):
        lines.append(f'bootstrap: ["{DOH_BOOTSTRAP_IP}:53"]')
    lines.append("cache: true")
    return "\n".join(lines) + "\n"
