"""
hostapd configuration generator.

Produces /etc/hostapd/hostapd.conf which configures the wireless access
point(s). One SSID is created per VLAN that has a wireless entry.

Key design decisions:
  - Each SSID gets a virtual AP interface (wlan0_vlan10, wlan0_vlan20, etc.)
    bridged to the corresponding VLAN subinterface via a Linux bridge.
  - The bridge is the interface hostapd uses — not the VAP directly.
  - All VAPs share the same physical radio (same channel/band).
  - WPA3 uses SAE; WPA2/3 uses SAE+PSK transition mode.
  - Open networks get no security block.

Hardware requirement:
  The physical interface must support AP mode and virtual interfaces.
  Check with: iw list | grep -A 10 "Supported interface modes"
"""

SECURITY_COMMENT = {
    "open":    "Open network — no encryption",
    "wpa2":    "WPA2-PSK (AES/CCMP)",
    "wpa3":    "WPA3-SAE",
    "wpa2/3":  "WPA2/WPA3 transition mode",
}

# hostapd hardware_mode values
BAND_TO_HW_MODE = {
    "2.4": "g",
    "5":   "a",
}


def _channel_block(ssid: dict) -> list[str]:
    """Return hostapd channel configuration lines."""
    band    = ssid.get("band", "2.4")
    channel = ssid.get("channel", "auto")
    lines   = [f"hw_mode={BAND_TO_HW_MODE.get(band, 'g')}"]

    if channel == "auto":
        # ACS (Automatic Channel Selection) — requires driver support.
        # Fall back to safe defaults if ACS unavailable.
        if band == "2.4":
            lines += ["channel=6", "# channel=0  # uncomment for ACS if supported"]
        else:
            lines += ["channel=36", "# channel=0  # uncomment for ACS if supported"]
    else:
        lines.append(f"channel={channel}")

    # 802.11n/ac/ax capabilities
    if band == "2.4":
        lines += [
            "ieee80211n=1",
            "ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]",
        ]
    else:
        lines += [
            "ieee80211n=1",
            "ieee80211ac=1",
            "ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]",
            "vht_capab=[SHORT-GI-80]",
        ]

    return lines


def _security_block(ssid: dict) -> list[str]:
    """Return hostapd security configuration lines."""
    security = ssid.get("security", "wpa2")
    password = ssid.get("password", "")

    if security == "open":
        return []

    lines = []
    if security == "wpa2":
        lines += [
            "wpa=2",
            "wpa_key_mgmt=WPA-PSK",
            "rsn_pairwise=CCMP",
            f"wpa_passphrase={password}",
        ]
    elif security == "wpa3":
        lines += [
            "wpa=2",
            "wpa_key_mgmt=SAE",
            "rsn_pairwise=CCMP",
            f"sae_password={password}",
            "ieee80211w=2",          # PMF required for WPA3
        ]
    elif security == "wpa2/3":
        lines += [
            "wpa=2",
            "wpa_key_mgmt=WPA-PSK SAE",
            "rsn_pairwise=CCMP",
            f"wpa_passphrase={password}",
            f"sae_password={password}",
            "ieee80211w=1",          # PMF optional (transition mode)
        ]

    return lines


def _vap_name(base_if: str, vlan_id: int) -> str:
    """Return the virtual AP interface name for a given VLAN."""
    return f"{base_if}_vlan{vlan_id}"


def _bridge_name(vlan_id: int) -> str:
    """Return the bridge interface name for a given VLAN."""
    return f"br-vlan{vlan_id}"


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/hostapd/hostapd.conf.

    Args:
        state: Full router state dict from state.load_state()

    Returns:
        hostapd config string, or empty string if wireless is disabled
        or no SSIDs are configured.
    """
    wireless = state.get("wireless", {})
    if not wireless.get("enabled"):
        return ""

    known_vlans  = {v["vlan_id"] for v in state.get("vlans", [])}
    ssids        = [
        s for s in wireless.get("ssids", [])
        if s.get("enabled", True) and s.get("vlan_id") in known_vlans
    ]
    base_if      = wireless.get("interface", "wlan0")
    country_code = wireless.get("country_code", "US")

    if not ssids:
        return ""

    # Validate: all SSIDs must use the same band/channel (shared radio)
    bands    = {s.get("band", "2.4") for s in ssids}
    channels = {s.get("channel", "auto") for s in ssids if s.get("channel", "auto") != "auto"}

    lines = [
        "# Generated by spud-router — do not edit manually",
        f"# {len(ssids)} SSID(s) on {base_if}",
        "",
        f"country_code={country_code}",
        "ieee80211d=1",
        "ieee80211h=1",
        "",
    ]

    # First SSID is the "primary" — sets radio config for all VAPs
    primary = ssids[0]
    primary_vap = _vap_name(base_if, primary["vlan_id"])
    bridge      = _bridge_name(primary["vlan_id"])

    lines += [
        "# ── Primary interface ──────────────────────────────────────────",
        f"interface={primary_vap}",
        f"bridge={bridge}",
        f"driver=nl80211",
        "",
        f"ssid={primary['ssid']}",
        f"ignore_broadcast_ssid={'1' if primary.get('hidden') else '0'}",
        "",
    ]

    # Channel / band (shared across all VAPs)
    lines += _channel_block(primary)
    lines += [""]

    # Security for primary
    sec_lines = _security_block(primary)
    if sec_lines:
        lines += [f"# {SECURITY_COMMENT.get(primary.get('security','wpa2'), '')}"]
        lines += sec_lines
    lines += [""]

    # Additional SSIDs as virtual BSSes
    for ssid in ssids[1:]:
        vap    = _vap_name(base_if, ssid["vlan_id"])
        bridge = _bridge_name(ssid["vlan_id"])
        lines += [
            "# ── Additional SSID ──────────────────────────────────────────",
            f"bss={vap}",
            f"bridge={bridge}",
            "",
            f"ssid={ssid['ssid']}",
            f"ignore_broadcast_ssid={'1' if ssid.get('hidden') else '0'}",
            "",
        ]
        sec_lines = _security_block(ssid)
        if sec_lines:
            lines += [f"# {SECURITY_COMMENT.get(ssid.get('security','wpa2'), '')}"]
            lines += sec_lines
        lines += [""]

    return "\n".join(lines)


def vap_interfaces(state: dict) -> list[dict]:
    """
    Return a list of VAP interface descriptors needed by the netplan generator.

    Each dict has:
        vap:     virtual AP interface name  (e.g. wlan0_vlan10)
        bridge:  bridge interface name      (e.g. br-vlan10)
        vlan_if: VLAN subinterface name     (e.g. eth0.10)
        vlan_id: VLAN ID
    """
    wireless = state.get("wireless", {})
    if not wireless.get("enabled"):
        return []

    base_if = wireless.get("interface", "wlan0")
    ssids   = [s for s in wireless.get("ssids", []) if s.get("enabled", True)]
    vlans   = {v["vlan_id"]: v for v in state.get("vlans", [])}
    result  = []

    for ssid in ssids:
        vlan_id = ssid["vlan_id"]
        if vlan_id not in vlans:
            continue  # SSID references a non-existent VLAN — skip
        vlan    = vlans[vlan_id]
        result.append({
            "vap":     _vap_name(base_if, vlan_id),
            "bridge":  _bridge_name(vlan_id),
            "vlan_if": f"{vlan['interface']}.{vlan_id}",
            "vlan_id": vlan_id,
        })

    return result
