"""
iptables rules generator.

Produces a bash script that configures the firewall:
  - Default policies: INPUT DROP, FORWARD DROP, OUTPUT ACCEPT
  - Always-open: loopback, established/related
  - Always-open on LAN: DNS (53 tcp/udp), DHCP (67 udp)
  - Management interface: SSH, web UI, DNS, DHCP (egress always allowed —
    not subject to outbound rules, so admin access can't be locked out)
  - Tailscale interface (if enabled)
  - NAT masquerade on WAN
  - Wireless bridge interfaces (same DNS/DHCP + egress/inter-VLAN treatment
    as their VLAN)
  - Outbound (egress): LAN VLANs → WAN
  - Inter-VLAN forwarding: auto-mesh (non-isolated) or explicit rules
  - User-defined inbound rules
  - IP forwarding enabled

Two inter-VLAN modes:
  - Auto mode: no user inter-VLAN rules → non-isolated VLANs are fully meshed
  - Explicit mode: any user inter-VLAN rule exists → default deny, only
    configured rules are allowed

Outbound (egress) evaluation, per LAN VLAN, first-match:
  1. User fw_outbound rules matching that VLAN, in list order (optional
     destination CIDR + proto/port; accept or drop).
  2. The fw_outbound_default fallback ("allow" → ACCEPT, "deny" → DROP).
  Scoped to `-o {wan}` only — management-interface egress and tailscale0
  egress are separate concerns and are not affected by these rules.
"""
from . import hostapd as hostapd_gen


def _proto_port_flags(rule: dict) -> str:
    """Return iptables match flags for protocol and optional port."""
    proto = rule.get("proto", "any")
    port  = rule.get("port")
    if not proto or proto == "any":
        return ""
    flags = f"-p {proto}"
    if port:
        flags += f" --dport {port}"
    return flags


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/spud-router/iptables.sh.

    Args:
        state: Full router state dict from state.load_state()

    Returns:
        Bash script string ready to write to disk and execute.
    """
    router    = state.get("router", {})
    vlans     = state.get("vlans", [])
    fw_in     = state.get("fw_inbound", [])
    fw_iv     = state.get("fw_intervlan", [])
    tailscale = state.get("tailscale", {})

    wan          = router.get("wan_interface", "eth1")
    mgmt_enabled = router.get("mgmt_enabled", False)
    mgmt_if      = router.get("mgmt_interface", "eth0")

    # Map vlan_id → subinterface name for convenience
    vlan_map = {v["vlan_id"]: f"{v['interface']}.{v['vlan_id']}" for v in vlans}

    lines = [
        "#!/bin/bash",
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "IPT=iptables",
        "",
        "# ── Flush ───────────────────────────────────────────────────────────",
        "$IPT -F",
        "$IPT -t nat -F",
        "$IPT -X",
        "",
        "# ── Default policies ────────────────────────────────────────────────",
        "$IPT -P INPUT DROP",
        "$IPT -P FORWARD DROP",
        "$IPT -P OUTPUT ACCEPT",
        "",
        "# ── Always allow: loopback & established ────────────────────────────",
        "$IPT -A INPUT -i lo -j ACCEPT",
        "$IPT -A INPUT  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
        "$IPT -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
        "",
    ]

    # Built-in: DNS + DHCP always open on all LAN VLANs (skip WAN VLAN)
    lines.append("# ── Built-in: DNS & DHCP on all LAN VLANs ──────────────────")
    for vlan in vlans:
        # Skip WAN VLAN (no IP address)
        if not vlan.get('ip_address'):
            continue
        si = vlan_map[vlan["vlan_id"]]
        lines += [
            f"$IPT -A INPUT -i {si} -p udp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {si} -p tcp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {si} -p udp --dport 67 -j ACCEPT",
        ]
    lines.append("")

    # Management interface
    if mgmt_enabled:
        lines += [
            "# ── Management interface (untagged access) ───────────────────────",
            f"$IPT -A INPUT -i {mgmt_if} -p udp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p tcp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p udp --dport 67 -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p tcp --dport 22   -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p tcp --dport 8080 -j ACCEPT",
            f"$IPT -A FORWARD -i {mgmt_if} -o {wan} -j ACCEPT",
            "",
        ]

    # Web UI access on LAN VLANs
    lines.append("# ── Web UI on LAN VLANs ──────────────────────────────────────────")
    for vlan in vlans:
        # Skip WAN VLAN (no IP address)
        if not vlan.get('ip_address'):
            continue
        si = vlan_map[vlan["vlan_id"]]
        lines.append(f"$IPT -A INPUT -i {si} -p tcp --dport 8080 -j ACCEPT")
    lines.append("")

    # User-defined inbound rules
    if fw_in:
        lines.append("# ── User inbound rules ──────────────────────────────────────")
        for rule in fw_in:
            vid     = rule.get("vlan_id", 0)
            # For vlan_id=0 (all VLANs), only apply to LAN VLANs (skip WAN VLAN)
            if vid == 0:
                targets = [vlan_map[v["vlan_id"]] for v in vlans if v.get('ip_address')]
            else:
                targets = [vlan_map[vid]] if vid in vlan_map else []
            pp      = _proto_port_flags(rule)
            action  = rule.get("action", "accept").upper()
            raw_desc = rule.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment = f"  # {safe_desc}" if safe_desc else ""
            for si in targets:
                rule_line = f"$IPT -A INPUT -i {si}"
                if pp:
                    rule_line += f" {pp}"
                rule_line += f" -j {action}{comment}"
                lines.append(rule_line)
        lines.append("")

    # Tailscale
    if tailscale.get("enabled"):
        lines += [
            "# ── Tailscale ────────────────────────────────────────────────────",
            "$IPT -A INPUT   -i tailscale0 -j ACCEPT",
            "$IPT -A FORWARD -i tailscale0 -j ACCEPT",
            "$IPT -A FORWARD -o tailscale0 -j ACCEPT",
            "",
        ]

    # NAT masquerade
    lines += [
        "# ── NAT masquerade ───────────────────────────────────────────────────",
        f"$IPT -t nat -A POSTROUTING -o {wan} -j MASQUERADE",
        "",
    ]

    # Wireless bridge interfaces get the same built-in DNS/DHCP access as
    # their VLAN. (Bridge → WAN forwarding is handled below, in the egress
    # section, via all_ifs_for_vlan() — same as every other LAN interface.)
    vap_list = hostapd_gen.vap_interfaces(state)
    if vap_list:
        lines.append("# ── Wireless bridges: DNS/DHCP ───────────────────────────────")
        for vap in vap_list:
            lines += [
                f"$IPT -A INPUT   -i {vap['bridge']} -p udp --dport 53 -j ACCEPT",
                f"$IPT -A INPUT   -i {vap['bridge']} -p tcp --dport 53 -j ACCEPT",
                f"$IPT -A INPUT   -i {vap['bridge']} -p udp --dport 67 -j ACCEPT",
            ]
        lines.append("")

    # Build a complete interface map: vlan_id → [subif, bridge_if_if_any]
    # This ensures wireless clients get the same egress/inter-VLAN treatment
    # as wired clients on the same VLAN.
    bridge_map = {vap["vlan_id"]: vap["bridge"] for vap in vap_list}

    def all_ifs_for_vlan(vlan_id: int) -> list[str]:
        """Return all interfaces (wired + wireless bridge) for a VLAN."""
        result = []
        if vlan_id in vlan_map:
            result.append(vlan_map[vlan_id])
        if vlan_id in bridge_map:
            result.append(bridge_map[vlan_id])
        return result

    # Outbound (egress): LAN VLANs → WAN. First-match per VLAN: user
    # fw_outbound rules in list order, then the per-policy fallback
    # (ACCEPT for "allow", DROP for "deny"). Scoped to `-o {wan}` only —
    # management-interface egress (above) and tailscale0 egress (below) are
    # separate concerns and untouched here.
    fw_out         = state.get("fw_outbound", [])
    fw_out_default = state.get("fw_outbound_default", "allow")
    fallback_action = "DROP" if fw_out_default == "deny" else "ACCEPT"

    lines.append("# ── Outbound (egress): LAN VLANs → WAN ────────────────────────")
    for vlan in vlans:
        # Skip WAN VLAN (no IP address)
        if not vlan.get('ip_address'):
            continue
        vid = vlan["vlan_id"]
        ifs = all_ifs_for_vlan(vid)

        for rule in fw_out:
            rvid = rule.get("vlan_id", 0)
            if rvid != 0 and rvid != vid:
                continue
            dest    = rule.get("dest", "")
            pp      = _proto_port_flags(rule)
            action  = rule.get("action", "accept").upper()
            raw_desc = rule.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment = f"  # {safe_desc}" if safe_desc else ""
            for si in ifs:
                rule_line = f"$IPT -A FORWARD -i {si} -o {wan}"
                if dest:
                    rule_line += f" -d {dest}"
                if pp:
                    rule_line += f" {pp}"
                rule_line += f" -j {action}{comment}"
                lines.append(rule_line)

        for si in ifs:
            lines.append(f"$IPT -A FORWARD -i {si} -o {wan} -j {fallback_action}")
    lines.append("")

    # Inter-VLAN forwarding
    lines.append("# ── Inter-VLAN forwarding ────────────────────────────────────")
    has_user_iv_rules = len(fw_iv) > 0

    if not has_user_iv_rules:
        # Auto mode: non-isolated LAN VLANs are fully meshed (skip WAN VLAN)
        lines.append("# Auto mode — non-isolated LAN VLANs meshed")
        for vlan in vlans:
            # Skip WAN VLAN (no IP address)
            if not vlan.get('ip_address'):
                continue
            if vlan.get("isolate"):
                continue
            for other in vlans:
                # Skip WAN VLAN and self
                if not other.get('ip_address') or other["vlan_id"] == vlan["vlan_id"] or other.get("isolate"):
                    continue
                for fi in all_ifs_for_vlan(vlan["vlan_id"]):
                    for ti in all_ifs_for_vlan(other["vlan_id"]):
                        lines.append(f"$IPT -A FORWARD -i {fi} -o {ti} -j ACCEPT")
    else:
        # Explicit mode: only user-defined rules (skip WAN VLAN)
        lines.append("# Explicit mode — user-defined rules only (default deny)")
        non_isolated = [v for v in vlans if v.get('ip_address') and not v.get("isolate")]
        for rule in fw_iv:
            fvid   = rule.get("from_vlan", 0)
            tvid   = rule.get("to_vlan", 0)
            action = rule.get("action", "accept").upper()
            pp     = _proto_port_flags(rule)
            raw_desc = rule.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment = f"  # {safe_desc}" if safe_desc else ""

            from_ifs = (
                [fi for v in non_isolated for fi in all_ifs_for_vlan(v["vlan_id"])]
                if fvid == 0
                else all_ifs_for_vlan(fvid)
            )
            to_ifs = (
                [fi for v in non_isolated for fi in all_ifs_for_vlan(v["vlan_id"])]
                if tvid == 0
                else all_ifs_for_vlan(tvid)
            )

            for fi in from_ifs:
                for ti in to_ifs:
                    if fi == ti:
                        continue
                    rule_line = f"$IPT -A FORWARD -i {fi} -o {ti}"
                    if pp:
                        rule_line += f" {pp}"
                    rule_line += f" -j {action}{comment}"
                    lines.append(rule_line)

    lines += [
        "",
        "# ── Enable IP forwarding ─────────────────────────────────────────────",
        "echo 1 > /proc/sys/net/ipv4/ip_forward",
        "",
        "# ── Persist IP forwarding across reboots ─────────────────────────────",
        'cat > /etc/sysctl.d/99-spud-router.conf << "EOF"',
        "net.ipv4.ip_forward = 1",
        "EOF",
        "",
        "# ── Persist rules for iptables-persistent ────────────────────────────",
        "mkdir -p /etc/iptables",
        "iptables-save > /etc/iptables/rules.v4",
        "echo 'spud-router: iptables rules applied'",
    ]

    return "\n".join(lines) + "\n"
