# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
iptables rules generator.

Produces a bash script that configures the firewall:
  - Default policies: INPUT DROP, FORWARD DROP, OUTPUT ACCEPT
  - Always-open: loopback, established/related
  - Always-open on LAN: DNS (53 tcp/udp), DHCP (67 udp)
  - Management interface: SSH, web UI, DNS, DHCP (egress always allowed —
    not subject to outbound rules, so admin access can't be locked out)
  - VPN provider interfaces (Tailscale, and any future provider registered
    in VPN_PROVIDER_INTERFACES) — each enabled provider gets the identical
    INPUT/FORWARD/MASQUERADE treatment on its own interface, additively;
    multiple providers may be enabled and stacked at once
  - NAT masquerade on WAN
  - Port forwarding (DNAT): WAN port -> LAN host:port, with a matching
    FORWARD ACCEPT
  - Wireless bridge interfaces (same DNS/DHCP + egress/inter-VLAN treatment
    as their VLAN)
  - Outbound (egress): LAN VLANs → WAN
  - Inter-VLAN forwarding: auto-mesh (non-isolated) or explicit rules
  - User-defined inbound rules
  - IP forwarding enabled

Two inter-VLAN modes:
  - Auto mode: no user inter-VLAN rules → non-isolated VLANs are fully meshed
  - Explicit mode: any user inter-VLAN rule exists → default deny, only
    configured rules are allowed

Outbound (egress) evaluation, per LAN VLAN, first-match:
  1. User fw_outbound rules matching that VLAN, in list order (optional
     destination CIDR + proto/port; accept or drop).
  2. The fw_outbound_default fallback ("allow" → ACCEPT, "deny" → DROP).
  Scoped to `-o {wan}` only — management-interface egress and tailscale0
  egress are separate concerns and are not affected by these rules.
"""
from . import doh as doh_gen
from . import hostapd as hostapd_gen

# Every VPN provider gets identical firewall treatment on its own OS
# interface — state key -> interface name. A provider adds one entry here
# when it lands, and the loop below stacks them additively — multiple
# providers can be enabled at once with no interaction between their rules.
VPN_PROVIDER_INTERFACES = {
    "tailscale": "tailscale0",
    "wireguard": "wg0",
    "nebula": "nebula1",
}


def _proto_port_flags(rule: dict) -> str:
    """Return iptables match flags for protocol and optional port."""
    proto = rule.get("proto", "any")
    port  = rule.get("port")
    if not proto or proto == "any":
        return ""
    if proto == "icmp":
        flags = "-p icmp"
        icmp_type = rule.get("icmp_type")
        icmp_code = rule.get("icmp_code")
        # icmp_type/icmp_code are validated (whitelist name or 0-255 int) by
        # BaseFirewallRule — safe to interpolate directly.
        if icmp_type and icmp_type != "any":
            flags += f" --icmp-type {icmp_type}"
            if icmp_code is not None:
                flags += f"/{icmp_code}"
        return flags
    flags = f"-p {proto}"
    if port:
        flags += f" --dport {port}"
    return flags


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/spud-router/iptables.sh.

    Args:
        state: Full router state dict from state.load_state()

    Returns:
        Bash script string ready to write to disk and execute.
    """
    router    = state.get("router", {})
    vlans     = state.get("vlans", [])
    fw_in     = state.get("fw_inbound", [])
    fw_iv     = state.get("fw_intervlan", [])

    wan          = router.get("wan_interface", "eth1")
    mgmt_enabled = router.get("mgmt_enabled", False)
    mgmt_if      = router.get("mgmt_interface", "eth0")

    # Map vlan_id → subinterface name for convenience. vlan_id == 0 is the
    # "untagged / physical interface" sentinel (#195, multi-NIC installs) —
    # the bare NIC name is used directly rather than a tagged subinterface.
    def _subif_name(v: dict) -> str:
        return v["interface"] if v.get("vlan_id") == 0 else f"{v['interface']}.{v['vlan_id']}"

    vlan_map = {v["vlan_id"]: _subif_name(v) for v in vlans}
    vap_list = hostapd_gen.vap_interfaces(state)
    bridge_map = {vap["vlan_id"]: vap["bridge"] for vap in vap_list}

    def all_ifs_for_vlan(vlan_id: int) -> list[str]:
        """Return all interfaces (wired + wireless bridge) for a VLAN."""
        result = []
        if vlan_id in vlan_map:
            result.append(vlan_map[vlan_id])
        if vlan_id in bridge_map:
            result.append(bridge_map[vlan_id])
        return result

    lines = [
        "#!/bin/bash",
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "IPT=iptables",
        "",
        "# ── Flush ───────────────────────────────────────────────────────────",
        "$IPT -F",
        "$IPT -t nat -F",
        # raw PREROUTING is spud-router's alone (tailscale uses filter+nat only)
        # — flush it so the ping DROP rules below rebuild cleanly each apply.
        "$IPT -t raw -F PREROUTING",
        "$IPT -X",
        "",
        "# ── Default policies ────────────────────────────────────────────────",
        "$IPT -P INPUT DROP",
        "$IPT -P FORWARD DROP",
        "$IPT -P OUTPUT ACCEPT",
        "",
        "# ── Always allow: loopback & established ────────────────────────────",
        "$IPT -A INPUT -i lo -j ACCEPT",
    ]

    # Ping (ICMP echo) policy — matched by DESTINATION IP, not input
    # interface (#164): Linux's weak host model answers ICMP for any local IP
    # on any interface, so "ping off" must govern the IP from every path.
    #
    # When BLOCKED, the drop is emitted in the `raw` PREROUTING table, not
    # filter INPUT (#170). tailscaled inserts its own `-A INPUT -j ts-input`
    # (which blanket-accepts `-i tailscale0`) and its position in INPUT races
    # our flush-and-rebuild — when it lands ahead of our INPUT drop, a tailnet
    # ping is accepted before our rule is ever evaluated. raw PREROUTING runs
    # before conntrack AND before any filter/INPUT chain, so tailscale can't
    # order around it. A belt-and-suspenders INPUT drop stays too (covers the
    # in-flight/conntrack case and any non-tailscale path). When ALLOWED, an
    # INPUT accept opens the physical path (tailnet is already accepted by
    # ts-input).
    def _ip_only(addr: str) -> str:
        """Tolerate an IP stored with a CIDR suffix (e.g. "192.168.1.1/24")
        — iptables -d wants the bare address."""
        return addr.split("/")[0]

    def _ping_rules(ip: str, allowed: bool) -> list[str]:
        if allowed:
            return [f"$IPT -A INPUT -d {ip} -p icmp --icmp-type echo-request -j ACCEPT"]
        return [
            f"$IPT -t raw -A PREROUTING -d {ip} -p icmp --icmp-type echo-request -j DROP",
            f"$IPT -A INPUT -d {ip} -p icmp --icmp-type echo-request -j DROP",
        ]

    mgmt_ip = router.get("mgmt_ip")
    if mgmt_enabled and mgmt_ip:
        lines.append("# ── Management IP ping policy ────────────────────────────────────")
        lines += _ping_rules(_ip_only(mgmt_ip), bool(router.get("mgmt_icmp_echo")))
        lines.append("")

    lan_vlans = [v for v in vlans if v.get("ip_address")]
    if lan_vlans:
        lines.append("# ── Per-VLAN IP ping (ICMP echo) ─────────────────────────────")
        for vlan in lan_vlans:
            lines += _ping_rules(_ip_only(vlan["ip_address"]), bool(vlan.get("icmp_echo")))
        lines.append("")

    lines += [
        "$IPT -A INPUT  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
        "$IPT -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
        "",
    ]

    # Built-in: DNS + DHCP always open on all LAN VLANs (skip WAN VLAN)
    lines.append("# ── Built-in: DNS & DHCP on all LAN VLANs ──────────────────")
    for vlan in vlans:
        # Skip WAN VLAN (no IP address)
        if not vlan.get('ip_address'):
            continue
        si = vlan_map[vlan["vlan_id"]]
        lines += [
            f"$IPT -A INPUT -i {si} -p udp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {si} -p tcp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {si} -p udp --dport 67 -j ACCEPT",
        ]
    lines.append("")

    # Management interface
    if mgmt_enabled:
        lines += [
            "# ── Management interface (untagged access) ───────────────────────",
            f"$IPT -A INPUT -i {mgmt_if} -p udp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p tcp --dport 53 -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p udp --dport 67 -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p tcp --dport 22   -j ACCEPT",
            f"$IPT -A INPUT -i {mgmt_if} -p tcp --dport 8080 -j ACCEPT",
            f"$IPT -A FORWARD -i {mgmt_if} -o {wan} -j ACCEPT",
            "",
        ]

    # Web UI access on LAN VLANs
    lines.append("# ── Web UI on LAN VLANs ──────────────────────────────────────────")
    for vlan in vlans:
        # Skip WAN VLAN (no IP address)
        if not vlan.get('ip_address'):
            continue
        si = vlan_map[vlan["vlan_id"]]
        lines.append(f"$IPT -A INPUT -i {si} -p tcp --dport 8080 -j ACCEPT")
    lines.append("")

    # SNMP: udp/161 is closed by INPUT's default DROP unless explicitly
    # enabled. snmpd.conf's own community/allowlist is the primary access
    # control (see generators/snmp.py); this only opens the port on LAN/mgmt
    # interfaces so that allowlisted pollers can actually reach it.
    if state.get("snmp", {}).get("enabled"):
        lines.append("# ── SNMP on LAN VLANs (allowlist enforced in snmpd.conf) ─────────")
        for vlan in vlans:
            if not vlan.get('ip_address'):
                continue
            si = vlan_map[vlan["vlan_id"]]
            lines.append(f"$IPT -A INPUT -i {si} -p udp --dport 161 -j ACCEPT")
        if mgmt_enabled:
            lines.append(f"$IPT -A INPUT -i {mgmt_if} -p udp --dport 161 -j ACCEPT")
        lines.append("")

    # User-defined inbound rules
    if fw_in:
        lines.append("# ── User inbound rules ──────────────────────────────────────")
        for rule in fw_in:
            vid     = rule.get("vlan_id", 0)
            # For vlan_id=0 (all VLANs), only apply to LAN VLANs (skip WAN VLAN).
            # NB: vlan_id=0 is overloaded — in a firewall rule it means "all LAN
            # networks", while in a VlanConfig it's the untagged-physical-port
            # sentinel (#195). They coincide harmlessly: an untagged LAN network
            # has an ip_address, so this "all LANs" branch includes it as one of
            # the targets, which is the intended behavior.
            if vid == 0:
                targets = [vlan_map[v["vlan_id"]] for v in vlans if v.get('ip_address')]
            else:
                targets = [vlan_map[vid]] if vid in vlan_map else []
            pp      = _proto_port_flags(rule)
            action  = rule.get("action", "accept").upper()
            raw_desc = rule.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment = f"  # {safe_desc}" if safe_desc else ""
            for si in targets:
                rule_line = f"$IPT -A INPUT -i {si}"
                if pp:
                    rule_line += f" {pp}"
                rule_line += f" -j {action}{comment}"
                lines.append(rule_line)
        lines.append("")

    # VPN providers: every enabled provider gets identical INPUT/FORWARD/
    # MASQUERADE treatment on its own interface — additive/stacked, so
    # multiple providers can run concurrently with no interaction between
    # their rules. (Subnet-router SNAT rationale, still specific to how
    # each provider's own subnet-routing feature works: without the
    # masquerade, a LAN client's traffic forwarded onto a VPN keeps its
    # real LAN source IP, which the remote side's ACL/routing has no
    # reason to accept or return to. This must be generated by us — not
    # left to the provider's own equivalent flag, e.g. Tailscale's
    # --snat-subnet-routes — because the top-of-script "$IPT -t nat -F"
    # flush wipes that provider-managed rule too, and it's only restored
    # on that provider's own reconcile cycle.)
    for provider_key, ifname in VPN_PROVIDER_INTERFACES.items():
        if not state.get(provider_key, {}).get("enabled"):
            continue
        lines += [
            f"# ── VPN: {provider_key} ({ifname}) ────────────────────────────────",
            f"$IPT -A INPUT   -i {ifname} -j ACCEPT",
            f"$IPT -A FORWARD -i {ifname} -j ACCEPT",
            f"$IPT -A FORWARD -o {ifname} -j ACCEPT",
            f"$IPT -t nat -A POSTROUTING -o {ifname} -j MASQUERADE",
            "",
        ]

    # WireGuard server/hub mode needs its UDP listen port reachable from the
    # WAN so remote peers can dial in; client mode only dials out (the
    # router is never the one accepting a fresh connection), so it doesn't
    # need this — OUTPUT's default ACCEPT policy already covers it.
    wireguard = state.get("wireguard", {})
    if wireguard.get("enabled") and wireguard.get("mode") == "server":
        listen_port = wireguard.get("listen_port", 51820)
        lines += [
            "# ── WireGuard: UDP listen port (server mode) ─────────────────────",
            f"$IPT -A INPUT -i {wan} -p udp --dport {listen_port} -j ACCEPT",
            "",
        ]

    # Nebula listens for peer/lighthouse punching regardless of role (there
    # is no server/client split like WireGuard's) — but only once it has a
    # complete cert/key/CA triple, same gate as generators/nebula.py and
    # nebula_apply.py use to decide whether the interface actually comes up.
    nebula = state.get("nebula", {})
    if nebula.get("enabled") and nebula.get("cert_pem") and nebula.get("key_pem") and nebula.get("ca_pem"):
        listen_port = nebula.get("listen_port", 4242)
        lines += [
            "# ── Nebula: UDP listen port ────────────────────────────────────────",
            f"$IPT -A INPUT -i {wan} -p udp --dport {listen_port} -j ACCEPT",
            "",
        ]

    # NAT masquerade
    lines += [
        "# ── NAT masquerade ───────────────────────────────────────────────────",
        f"$IPT -t nat -A POSTROUTING -o {wan} -j MASQUERADE",
        "",
    ]

    # Port forwarding (DNAT): WAN port -> LAN host:port. The nat PREROUTING
    # rule lives here with the other nat-table rules (nat rules aren't
    # order-sensitive relative to filter-table rules, so grouping for
    # readability is enough); the matching filter-table FORWARD ACCEPT is
    # emitted alongside it and — since this whole section runs well before
    # the Inter-VLAN forwarding section below — is guaranteed to be
    # evaluated before any explicit-mode default-deny FORWARD rule could
    # catch it. Return traffic is already covered by the WAN MASQUERADE
    # rule above, so nothing extra is needed for it. Only enabled forwards
    # are emitted; proto/ports/host all passed through PortForward's
    # validators before ever reaching here.
    port_forwards = [pf for pf in state.get("port_forwards", []) if pf.get("enabled", True)]
    if port_forwards:
        lines.append("# ── Port forwarding (DNAT) ───────────────────────────────────────────")
        for pf in port_forwards:
            proto     = pf.get("proto", "tcp")
            wan_port  = pf.get("wan_port")
            lan_host  = pf.get("lan_host")
            lan_port  = pf.get("lan_port")
            raw_desc  = pf.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment   = f"  # {safe_desc}" if safe_desc else ""
            lines.append(
                f"$IPT -t nat -A PREROUTING -i {wan} -p {proto} --dport {wan_port} "
                f"-j DNAT --to-destination {lan_host}:{lan_port}{comment}"
            )
            lines.append(
                f"$IPT -A FORWARD -i {wan} -p {proto} -d {lan_host} --dport {lan_port} "
                f"-j ACCEPT{comment}"
            )
        lines.append("")

    # DoH enforcement: block the router's own plaintext DNS to the WAN.
    # Only ever emitted when wan_dns_mode == "doh" AND block_wan_dns is set
    # (never in auto/manual mode — that would cause a DNS outage). This is
    # independent of the per-VLAN block below: this blocks the router's own
    # OUTPUT, not LAN clients' FORWARD traffic. dnsmasq's query to
    # 127.0.0.1:5053 (dnsproxy) stays on lo and is unaffected; dnsproxy
    # itself talks :443 to the WAN, a different port, also unaffected.
    block_wan_dns_active = router.get("block_wan_dns", False) and router.get("wan_dns_mode") == "doh"
    if block_wan_dns_active:
        # A custom DoH upstream may be a hostname that dnsproxy must resolve
        # via a plaintext bootstrap lookup before it can dial the DoH
        # endpoint — but the OUTPUT REJECT below would otherwise block that
        # one lookup too, deadlocking DNS entirely. Built-in providers are
        # IP-literal (generators/doh.py) and never hit this path. This is a
        # narrow hole in the router's OWN OUTPUT, to the ONE fixed bootstrap
        # resolver, only when actually needed — LAN clients' own FORWARD
        # :53 block (below, per-VLAN) is completely untouched.
        upstream = doh_gen.resolve_upstream_url(router)
        if doh_gen.upstream_needs_bootstrap(upstream):
            lines += [
                "# ── DoH bootstrap: allow router's own plaintext lookup ───────────────",
                f"$IPT -A OUTPUT -o {wan} -p udp --dport 53 -d {doh_gen.DOH_BOOTSTRAP_IP} -j ACCEPT",
                f"$IPT -A OUTPUT -o {wan} -p tcp --dport 53 -d {doh_gen.DOH_BOOTSTRAP_IP} -j ACCEPT",
                "",
            ]
        lines += [
            "# ── DoH enforcement: block router's own plaintext DNS to WAN ─────────",
            f"$IPT -A OUTPUT -o {wan} -p udp --dport 53 -j REJECT",
            f"$IPT -A OUTPUT -o {wan} -p tcp --dport 53 -j REJECT",
            "",
        ]

    # Wireless bridge interfaces get the same built-in DNS/DHCP access as
    # their VLAN. (Bridge → WAN forwarding is handled below, in the egress
    # section, via all_ifs_for_vlan() — same as every other LAN interface.)
    if vap_list:
        lines.append("# ── Wireless bridges: DNS/DHCP ───────────────────────────────")
        for vap in vap_list:
            lines += [
                f"$IPT -A INPUT   -i {vap['bridge']} -p udp --dport 53 -j ACCEPT",
                f"$IPT -A INPUT   -i {vap['bridge']} -p tcp --dport 53 -j ACCEPT",
                f"$IPT -A INPUT   -i {vap['bridge']} -p udp --dport 67 -j ACCEPT",
            ]
        lines.append("")

    # Outbound (egress): LAN VLANs → WAN. First-match per VLAN: user
    # fw_outbound rules in list order, then the per-policy fallback
    # (ACCEPT for "allow", DROP for "deny"). Scoped to `-o {wan}` only —
    # management-interface egress (above) and tailscale0 egress (below) are
    # separate concerns and untouched here.
    fw_out         = state.get("fw_outbound", [])
    fw_out_default = state.get("fw_outbound_default", "allow")
    fallback_action = "DROP" if fw_out_default == "deny" else "ACCEPT"

    lines.append("# ── Outbound (egress): LAN VLANs → WAN ────────────────────────")
    for vlan in vlans:
        # Skip WAN VLAN (no IP address)
        if not vlan.get('ip_address'):
            continue
        vid = vlan["vlan_id"]
        ifs = all_ifs_for_vlan(vid)

        # DoH enforcement: block LAN clients' plaintext :53 to the WAN,
        # ahead of any user-defined fw_out rule, so a permissive catch-all
        # allow can't silently bypass it.
        if block_wan_dns_active:
            for si in ifs:
                lines.append(f"$IPT -A FORWARD -i {si} -o {wan} -p udp --dport 53 -j REJECT")
                lines.append(f"$IPT -A FORWARD -i {si} -o {wan} -p tcp --dport 53 -j REJECT")

        for rule in fw_out:
            rvid = rule.get("vlan_id", 0)
            if rvid != 0 and rvid != vid:
                continue
            dest    = rule.get("dest", "")
            pp      = _proto_port_flags(rule)
            action  = rule.get("action", "accept").upper()
            raw_desc = rule.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment = f"  # {safe_desc}" if safe_desc else ""
            for si in ifs:
                rule_line = f"$IPT -A FORWARD -i {si} -o {wan}"
                if dest:
                    rule_line += f" -d {dest}"
                if pp:
                    rule_line += f" {pp}"
                rule_line += f" -j {action}{comment}"
                lines.append(rule_line)

        for si in ifs:
            lines.append(f"$IPT -A FORWARD -i {si} -o {wan} -j {fallback_action}")
    lines.append("")

    # Inter-VLAN forwarding
    lines.append("# ── Inter-VLAN forwarding ────────────────────────────────────")
    has_user_iv_rules = len(fw_iv) > 0

    if not has_user_iv_rules:
        # Auto mode: non-isolated LAN VLANs are fully meshed (skip WAN VLAN)
        lines.append("# Auto mode — non-isolated LAN VLANs meshed")
        for vlan in vlans:
            # Skip WAN VLAN (no IP address)
            if not vlan.get('ip_address'):
                continue
            if vlan.get("isolate"):
                continue
            for other in vlans:
                # Skip WAN VLAN and self
                if not other.get('ip_address') or other["vlan_id"] == vlan["vlan_id"] or other.get("isolate"):
                    continue
                for fi in all_ifs_for_vlan(vlan["vlan_id"]):
                    for ti in all_ifs_for_vlan(other["vlan_id"]):
                        lines.append(f"$IPT -A FORWARD -i {fi} -o {ti} -j ACCEPT")
    else:
        # Explicit mode: only user-defined rules (skip WAN VLAN)
        lines.append("# Explicit mode — user-defined rules only (default deny)")
        non_isolated = [v for v in vlans if v.get('ip_address') and not v.get("isolate")]
        for rule in fw_iv:
            fvid   = rule.get("from_vlan", 0)
            tvid   = rule.get("to_vlan", 0)
            action = rule.get("action", "accept").upper()
            pp     = _proto_port_flags(rule)
            raw_desc = rule.get("description", "")
            safe_desc = raw_desc.replace("\n", " ").replace("\r", " ") if raw_desc else ""
            comment = f"  # {safe_desc}" if safe_desc else ""

            from_ifs = (
                [fi for v in non_isolated for fi in all_ifs_for_vlan(v["vlan_id"])]
                if fvid == 0
                else all_ifs_for_vlan(fvid)
            )
            to_ifs = (
                [fi for v in non_isolated for fi in all_ifs_for_vlan(v["vlan_id"])]
                if tvid == 0
                else all_ifs_for_vlan(tvid)
            )

            for fi in from_ifs:
                for ti in to_ifs:
                    if fi == ti:
                        continue
                    rule_line = f"$IPT -A FORWARD -i {fi} -o {ti}"
                    if pp:
                        rule_line += f" {pp}"
                    rule_line += f" -j {action}{comment}"
                    lines.append(rule_line)

    lines += [
        "",
        "# ── Enable IP forwarding ─────────────────────────────────────────────",
        "echo 1 > /proc/sys/net/ipv4/ip_forward",
        "",
        "# ── Allow unprivileged ICMP ping sockets (SOCK_DGRAM ICMP, Linux's ─────",
        "# \"ping socket\" feature) — lets the spud-router service (running as ────",
        "# the unprivileged spud-router user, no CAP_NET_RAW) issue pings for ────",
        "# the diagnostics endpoint without needing root or a setuid ping binary.",
        "echo \"0 2147483647\" > /proc/sys/net/ipv4/ping_group_range",
        "",
        "# ── Persist IP forwarding & ping_group_range across reboots ──────────",
        'cat > /etc/sysctl.d/99-spud-router.conf << "EOF"',
        "net.ipv4.ip_forward = 1",
        "net.ipv4.ping_group_range = 0 2147483647",
        "EOF",
        "",
        "# ── Persist rules for iptables-persistent ────────────────────────────",
        "mkdir -p /etc/iptables",
        "iptables-save > /etc/iptables/rules.v4",
        "echo 'spud-router: iptables rules applied'",
    ]

    return "\n".join(lines) + "\n"
