# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
Nebula config.yaml generator.

Scope is join-only (#91): this device is never a lighthouse and never a
CA/signing authority, so `lighthouse.am_lighthouse` is always emitted as
`false` and there is no field for it in models.NebulaConfig — flipping it
would require this device to hold CA material it deliberately never has.

Hand-rolled YAML rather than a `pyyaml` dependency: Nebula's config schema
is small and stable, every value that reaches this module has already
been shape-validated by models.NebulaConfig/NebulaFirewallRule (IPs,
host:port pairs, port/proto whitelists), and every other generator in this
package is a pure string builder with no I/O or third-party deps.
"""
from pathlib import Path

CERT_DIR  = Path("/etc/nebula")
CA_PATH   = CERT_DIR / "ca.crt"
CERT_PATH = CERT_DIR / "host.crt"
KEY_PATH  = CERT_DIR / "host.key"


def _yaml_str(v: str) -> str:
    """Double-quoted YAML scalar with minimal escaping — every value passed
    through here is already whitelisted-shape (IP, host:port, port/proto
    token), so this only needs to handle the quote character itself."""
    return '"' + v.replace('"', '\\"') + '"'


def _firewall_rules_yaml(rules: list[dict]) -> list[str]:
    lines = []
    for rule in rules:
        lines.append(f"    - port: {rule.get('port', 'any')}")
        lines.append(f"      proto: {rule.get('proto', 'any')}")
        lines.append(f"      host: {_yaml_str(rule.get('host', 'any'))}")
    return lines


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/nebula/config.yaml. Returns "" when
    Nebula is disabled or its credentials (cert/key/CA) are incomplete —
    nebula_apply.apply() stops+disables the nebula unit in either case.
    """
    nb = state.get("nebula", {})
    if not nb.get("enabled"):
        return ""
    if not (nb.get("cert_pem") and nb.get("key_pem") and nb.get("ca_pem")):
        return ""

    lighthouse_hosts = nb.get("lighthouse_hosts", [])
    static_host_map  = nb.get("static_host_map", {})
    is_lighthouse_relay = bool(lighthouse_hosts)

    lines = [
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "",
        "pki:",
        f"  ca: {_yaml_str(str(CA_PATH))}",
        f"  cert: {_yaml_str(str(CERT_PATH))}",
        f"  key: {_yaml_str(str(KEY_PATH))}",
        "",
    ]

    if static_host_map:
        lines.append("static_host_map:")
        for nebula_ip, endpoints in static_host_map.items():
            endpoints_str = ", ".join(_yaml_str(e) for e in endpoints)
            lines.append(f"  {_yaml_str(nebula_ip)}: [{endpoints_str}]")
    else:
        lines.append("static_host_map: {}")
    lines.append("")

    lines += [
        "lighthouse:",
        # Join-only: this device is never itself a lighthouse (see module
        # docstring) — it only ever registers with one or more configured
        # below.
        "  am_lighthouse: false",
        "  interval: 60",
    ]
    if is_lighthouse_relay:
        lines.append("  hosts:")
        for host in lighthouse_hosts:
            lines.append(f"    - {_yaml_str(host)}")
    else:
        lines.append("  hosts: []")
    lines.append("")

    # Relay: a deterministic fallback path when two hosts can't punch a direct
    # tunnel (hard/symmetric NAT, or slow candidate convergence). Traffic flows
    # through a relay while nebula keeps trying direct, and upgrades to direct
    # automatically once it forms. `am_relay` lets this host forward relay
    # traffic for others; a relay is not a lighthouse and needs no CA material,
    # so this stays within the join-only scope. See issue #263.
    relays = nb.get("relays", [])
    lines += [
        "relay:",
        f"  am_relay: {'true' if nb.get('am_relay') else 'false'}",
        f"  use_relays: {'false' if nb.get('use_relays') is False else 'true'}",
    ]
    if relays:
        lines.append("  relays:")
        for relay_ip in relays:
            lines.append(f"    - {_yaml_str(relay_ip)}")
    else:
        lines.append("  relays: []")
    lines.append("")

    lines += [
        "listen:",
        "  host: 0.0.0.0",
        f"  port: {nb.get('listen_port', 4242)}",
        "",
        "punchy:",
        "  punch: true",
        "",
        "tun:",
        "  disabled: false",
        "  dev: nebula1",
        "  drop_local_broadcast: false",
        "  drop_multicast: false",
        "  tx_queue: 500",
        "  mtu: 1300",
        "",
        "logging:",
        "  level: info",
        "  format: text",
        "",
        "firewall:",
    ]
    outbound = nb.get("firewall_outbound", [])
    if outbound:
        lines.append("  outbound:")
        lines += _firewall_rules_yaml(outbound)
    else:
        lines.append("  outbound: []")

    inbound = nb.get("firewall_inbound", [])
    if inbound:
        lines.append("  inbound:")
        lines += _firewall_rules_yaml(inbound)
    else:
        lines.append("  inbound: []")

    return "\n".join(lines) + "\n"
