# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
Net-SNMP (snmpd.conf) generator.

state["snmp"] is validated by models.SnmpConfig before it ever reaches this
module — community strings are ASCII/whitespace-restricted, allowlist
entries are validated IPs/CIDRs, and bind_interface matches the standard
interface-name regex — so nothing here needs further escaping.

Caveat: bind_interface is written into agentAddress as
"udp:<interface>:161" using the interface *name*, not a resolved IP. This
generator is a pure function with no I/O, so it cannot resolve the
interface's current address here. Confirm this is accepted by the
installed snmpd version on target hardware; if not, bind_interface should
resolve to an IP before being handed to this generator.
"""


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/snmp/snmpd.conf.
    Returns "" when SNMP is disabled — apply() writes an empty/commented
    file (or stops the service) in that case.
    """
    snmp = state.get("snmp", {})
    if not snmp.get("enabled"):
        return ""

    community_ro   = snmp.get("community_ro", "")
    community_rw   = snmp.get("community_rw", "")
    allowlist      = snmp.get("allowlist", [])
    bind_interface = snmp.get("bind_interface", "")
    location       = snmp.get("location", "")
    contact        = snmp.get("contact", "")

    lines = [
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "",
    ]

    agent_address = f"udp:{bind_interface}:161" if bind_interface else "udp:161"
    lines.append(f"agentAddress {agent_address}")
    lines.append("")

    if allowlist:
        for source in allowlist:
            lines.append(f"rocommunity {community_ro} {source}")
    else:
        lines.append("# No allowlist configured — accepting SNMP polls from any source")
        lines.append(f"rocommunity {community_ro} default")

    if community_rw:
        if allowlist:
            for source in allowlist:
                lines.append(f"rwcommunity {community_rw} {source}")
        else:
            lines.append(f"rwcommunity {community_rw} default")

    lines.append("")
    if location:
        lines.append(f"sysLocation {location}")
    if contact:
        lines.append(f"sysContact {contact}")

    return "\n".join(lines) + "\n"
