# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
Net-SNMP (snmpd.conf) generator.

state["snmp"] is validated by models.SnmpConfig before it ever reaches this
module — community strings are ASCII/whitespace-restricted, allowlist
entries are validated IPs/CIDRs, and bind_interface matches the standard
interface-name regex — so nothing here needs further escaping.

bind_interface is written into agentAddress as "udp:<bind_interface>:161".
net-snmp rejects an interface *name* there (snmpd fails to start on
"udp:ens19:161" — verified on hardware, #216), so this value is expected to
already be a resolved IPv4 address (or empty → "udp:161", all interfaces).
This generator is a pure function with no I/O; the name→IP resolution — and
the fall-back to unbound when the interface has no address yet — lives in
apply_core._resolve_snmp_bind, which patches the state before it reaches here.
"""


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/snmp/snmpd.conf.
    Returns "" when SNMP is disabled — apply() writes an empty/commented
    file (or stops the service) in that case.
    """
    snmp = state.get("snmp", {})
    if not snmp.get("enabled"):
        return ""

    community_ro   = snmp.get("community_ro", "")
    community_rw   = snmp.get("community_rw", "")
    allowlist      = snmp.get("allowlist", [])
    bind_interface = snmp.get("bind_interface", "")
    location       = snmp.get("location", "")
    contact        = snmp.get("contact", "")

    lines = [
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "",
    ]

    agent_address = f"udp:{bind_interface}:161" if bind_interface else "udp:161"
    lines.append(f"agentAddress {agent_address}")
    lines.append("")

    if allowlist:
        for source in allowlist:
            lines.append(f"rocommunity {community_ro} {source}")
    else:
        lines.append("# No allowlist configured — accepting SNMP polls from any source")
        lines.append(f"rocommunity {community_ro} default")

    if community_rw:
        if allowlist:
            for source in allowlist:
                lines.append(f"rwcommunity {community_rw} {source}")
        else:
            lines.append(f"rwcommunity {community_rw} default")

    lines.append("")
    if location:
        lines.append(f"sysLocation {location}")
    if contact:
        lines.append(f"sysContact {contact}")

    return "\n".join(lines) + "\n"
