# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
rsyslog remote-forwarding drop-in generator.

Produces /etc/rsyslog.d/49-spud-router-remote.conf: a selector
("<facility>.<severity>") pointing at a remote syslog server. UDP uses a
single "@", TCP/TLS use "@@" (rsyslog's own syntax for stream vs datagram
delivery); TLS additionally sets the gtls stream-driver directives so the
connection is encrypted end-to-end (RFC 5425 framing).

The 49- prefix is deliberate: rsyslog loads drop-ins in lexical order, so this
must sort BEFORE Ubuntu's 50-default.conf ("*.* -/var/log/syslog") for a
keep_local=false rule's "& stop" to actually suppress the local copy — at 60-
the default rule had already written it (#217).

state["syslog"] is validated by models.SyslogConfig before it ever reaches
this module — facility/severity are whitelisted tokens and server/port are
bounds-checked, so nothing here needs further escaping.
"""


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/rsyslog.d/49-spud-router-remote.conf.
    Returns "" when syslog forwarding is disabled — apply() writes an
    empty/commented file in that case so toggling off actually stops
    forwarding.
    """
    syslog = state.get("syslog", {})
    if not syslog.get("enabled"):
        return ""

    facility = syslog.get("facility", "*")
    severity = syslog.get("severity", "*")
    server   = syslog.get("server", "")
    port     = syslog.get("port", 514)
    protocol = syslog.get("protocol", "udp")
    keep_local = syslog.get("keep_local", True)

    selector = f"{facility}.{severity}"

    lines = [
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "",
    ]

    if protocol == "tls":
        lines += [
            "# TLS transport (RFC 5425 framing)",
            "$DefaultNetstreamDriver gtls",
            "$DefaultNetstreamDriverCAFile /etc/ssl/certs/ca-certificates.crt",
            "$ActionSendStreamDriver gtls",
            "$ActionSendStreamDriverMode 1",
            "$ActionSendStreamDriverAuthMode x509/name",
            "",
        ]
        target = f"@@{server}:{port}"
    elif protocol == "tcp":
        target = f"@@{server}:{port}"
    else:
        target = f"@{server}:{port}"

    action = f"{selector} {target}"
    if not keep_local:
        # "& stop" halts further rule processing for matched messages, so
        # they're forwarded but not also written to the local log files.
        action += "\n& stop"
    lines.append(action)

    return "\n".join(lines) + "\n"
