# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Brett Benson (https://github.com/bensonbrett)
"""
WireGuard (wg-quick) config generator.

Produces /etc/wireguard/wg0.conf: an [Interface] section (this device's own
tunnel identity/address) followed by one [Peer] section per configured
peer. Works identically for "server"/hub mode (many peers, no fixed
Endpoint on most of them) and "client" mode (a single peer — the remote
server — usually with both Endpoint and AllowedIPs=0.0.0.0/0 for
route-all).

state["wireguard"] is validated by models.WireguardConfig/WireguardPeer
before it ever reaches this module — keys are whitelisted-shape base64,
addresses/allowed_ips are validated CIDRs, endpoint is a validated
host:port — so nothing here needs further escaping.
"""


def generate(state: dict) -> str:
    """
    Generate the contents of /etc/wireguard/wg0.conf.
    Returns "" when WireGuard is disabled — apply() stops+disables the
    wg-quick@wg0 unit in that case.
    """
    wg = state.get("wireguard", {})
    if not wg.get("enabled"):
        return ""

    lines = [
        "# Generated by spud-router — do not edit manually",
        "# Re-generate and apply via the web UI or spud-cli",
        "",
        "[Interface]",
        f"PrivateKey = {wg.get('private_key', '')}",
    ]
    if wg.get("address"):
        lines.append(f"Address = {wg['address']}")
    lines.append(f"ListenPort = {wg.get('listen_port', 51820)}")
    lines.append("")

    for peer in wg.get("peers", []):
        lines.append("[Peer]")
        if peer.get("name"):
            lines.append(f"# {peer['name']}")
        lines.append(f"PublicKey = {peer.get('public_key', '')}")
        allowed_ips = peer.get("allowed_ips", [])
        if allowed_ips:
            lines.append(f"AllowedIPs = {', '.join(allowed_ips)}")
        if peer.get("endpoint"):
            lines.append(f"Endpoint = {peer['endpoint']}")
        if peer.get("persistent_keepalive"):
            lines.append(f"PersistentKeepalive = {peer['persistent_keepalive']}")
        lines.append("")

    return "\n".join(lines) + "\n"
